Repository firecracker-microvm/firecracker, pull requests merged in 2018-11, with the labels that each got.

#658 Correct Open API spec link in SPECIFICATION.md
  SPECIFICATION.md
Labels: Documentation: Usage

#669 Add Cargo.lock to Git
  .gitignore
  Cargo.lock
Labels: Program: Build System, Quality: Improvement

#675 Preallocate Cmdline internal String
  kernel/src/cmdline/mod.rs
Labels: Performance: Memory

#657 Adding "Production Host Setup Recommendations" doc
  docs/prod-host-setup.md
Labels: Documentation: Usage, Security: Hardening

#674 Unifying log messages triggered by flushing metrics
  logger/src/lib.rs
  src/main.rs
  vmm/src/lib.rs
Labels: Feature: Metrics, Quality: Improvement

#671 vmm: log graceful / forceful termination
  vmm/src/lib.rs
Labels: Quality: Improvement

#689 Some non-breaking tweaks to `micro_http`
  micro_http/src/common/mod.rs
  micro_http/src/request.rs
  micro_http/src/response.rs
Labels: Feature: MMDS, Quality: Improvement

#699 Differentiate between SRegs related errors
  x86_64/src/regs.rs
Labels: Program: Operability, Quality: Improvement

#680 Fix hyperlink to public URI for a GitHub issue
  FAQ.md
  mmds/src/data_store.rs
Labels: Documentation: Usage, Quality: Bug

#709 CI: run unit tests sequentially
  tests/integration_tests/build/test_unittests.py
Labels: Quality: Automated Testing, Quality: CI

#698 fix(api-server): fix mmds PUT response status code
  CHANGELOG.md
  api_server/src/http_service.rs
  mmds/src/data_store.rs
  tests/integration_tests/functional/test_mmds.py
Labels: Feature: API, Feature: MMDS, Quality: Improvement
