Repository firecracker-microvm/firecracker, pull requests merged in 2018-12, with the labels that each got.

#712 getting-started: Only warn on nested virtualization
  docs/getting-started.md
Labels: Documentation: Usage, Quality: Bug

#681 Remove DeviceState from NetworkInterfaceConfig
  CHANGELOG.md
  api_server/src/http_service.rs
  api_server/src/request/net.rs
  api_server/swagger/firecracker.yaml
  tests/framework/resources.py
  vmm/src/lib.rs
  vmm/src/vmm_config/mod.rs
  vmm/src/vmm_config/net.rs
Labels: Feature: API, Quality: Improvement

#703 Add test_licenses.py which validates all rust, python, and shell file…
  tests/integration_tests/build/test_licenses.py
Labels: Documentation: Licensing, Quality: Automated Testing

#720 Fix typo in prod-host-setup docs
  docs/prod-host-setup.md
Labels: Documentation: Usage, Feature: Jailing

#729 Jailer: set default seccomp level to 2
  CHANGELOG.md
  jailer/src/lib.rs
Labels: Feature: Jailing, Feature: Seccomp, Security: Hardening

#734 docs: rename files to the GitHub standard names
  CHARTER.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  FAQ.md
  README.md
Labels: Contribute: Mechanics, Documentation: Usage

#735 Replacing matches with if let
  src/bin/jailer.rs
Labels: Program: Refactoring, Quality: Improvement

#733 fixing command in doc to contain '\' for user copy
  docs/jailer.md
Labels: Documentation: Usage, Quality: Bug

#713 fix swagger yaml to match the code
  api_server/swagger/firecracker.yaml
Labels: Documentation: Usage, Feature: API, Quality: Bug

#738 Updated example Curl commands to match default socket name
  docs/getting-started.md
Labels: Documentation: Usage, Quality: Bug

#676 Move generated code to directories with _gen suffix
  Cargo.lock
  cpuid/Cargo.toml
  cpuid/src/c3_template.rs
  cpuid/src/lib.rs
  cpuid/src/t2_template.rs
  devices/Cargo.toml
  devices/src/lib.rs
  devices/src/virtio/block.rs
  devices/src/virtio/net.rs
  devices/src/virtio/vhost/vsock.rs
  kvm/Cargo.toml
  kvm/src/cap.rs
  kvm/src/lib.rs
  kvm_gen/Cargo.toml
  kvm_gen/patches/0001-kvm_sys-fix-alignment-for-x86-kvm-structs.patch
  kvm_gen/patches/0002-kvm_sys-implement-Debug-trait-for-kvm_lapic_state.patch
  kvm_gen/patches/0003-kvm_sys-implement-PartialEq-for-kvm_msr_entry.patch
  kvm_gen/patches/0004-kvm_sys-implement-PartialEq-for-register.patch
  kvm_gen/src/lib.rs
  kvm_gen/src/x86/bindings.rs
  kvm_gen/tests/sanity.rs
  net_gen/Cargo.toml
  net_gen/src/if_tun.rs
  net_gen/src/iff.rs
  net_gen/src/inn.rs
  net_gen/src/lib.rs
  net_gen/src/sockios.rs
  net_util/Cargo.toml
  net_util/src/lib.rs
  net_util/src/tap.rs
  tests/integration_tests/build/test_coverage.py
  vhost_backend/Cargo.toml
  vhost_backend/src/lib.rs
  vhost_backend/src/vsock.rs
  vhost_gen/Cargo.toml
  vhost_gen/patches/0001-vhost-fix-alignment-for-vhost_memory.patch
  vhost_gen/src/lib.rs
  vhost_gen/src/vhost.rs
  virtio_gen/Cargo.toml
  virtio_gen/patches/0001-virtio_sys-removing-warning-on-packed-struct.patch
  virtio_gen/src/lib.rs
  virtio_gen/src/virtio_blk.rs
  virtio_gen/src/virtio_config.rs
  virtio_gen/src/virtio_ids.rs
  virtio_gen/src/virtio_net.rs
  virtio_gen/src/virtio_ring.rs
  x86_64/Cargo.toml
  x86_64/src/gdt.rs
  x86_64/src/interrupts.rs
  x86_64/src/lib.rs
  x86_64/src/regs.rs
Labels: Program: Refactoring

#731 Disable reliance on support of 1GB pages
  x86_64/src/layout.rs
  x86_64/src/regs.rs
Labels: Feature: Core Virtualization, Quality: Bug

#764 docs: add email list to README.md
  README.md
Labels: Contribute: Mechanics

#753 Fix typo in kvm docs
  kvm/src/lib.rs
Labels: Documentation: Usage, Quality: Bug

#768 mmds: return dictionary keys
  mmds/src/data_store.rs
  tests/integration_tests/functional/test_mmds.py
Labels: Feature: MMDS, Quality: Bug

#683 readme: clarify how to contact for security
  README.md
Labels: Documentation: Usage

#777 memory_model: improve access request address range validation
  memory_model/src/mmap.rs
Labels: Quality: Improvement

#772 Seccomp: tighten filters
  vmm/src/default_syscalls.rs
Labels: Feature: Seccomp, Security: Hardening

#788 swagger: remove InstanceHalt from actions
  api_server/swagger/firecracker.yaml
Labels: Feature: API, Quality: Bug

#725 Added instructions for a dev VM setup
  docs/dev-machine-setup.md
Labels: Documentation: Usage

#722 Dumbo: added some new unit tests to ns.rs (2)
  dumbo/src/ns.rs
Labels: Feature: MMDS, Quality: Improvement
