Repository firecracker-microvm/firecracker, pull requests merged in 2019-01, with the labels that each got.

#807 Replace Vec::set_len with explicit initialization
  vmm/src/lib.rs
Labels: Quality: Bug

#806 Added URL Decoding to API server (#794)
  CHANGELOG.md
  api_server/src/http_service.rs
Labels: Feature: API, Quality: Improvement

#793 Add Proper Error Handling to EpollHandler Trait
  devices/src/lib.rs
  devices/src/virtio/block.rs
  devices/src/virtio/net.rs
  devices/src/virtio/vhost/handle.rs
  vmm/src/lib.rs
Labels: Quality: Improvement

#840 Add getting started network setup
  docs/network-setup.md
Labels: Documentation: Usage

#854 pretty print panics
  CHANGELOG.md
  src/main.rs
Labels: Program: Usability

#843 Jailer: Allow 'none' device for cgroups
  jailer/src/cgroup.rs
Labels: Feature: Jailing

#810 log the Firecracker version at start-up
  CHANGELOG.md
  logger/src/error.rs
  logger/src/lib.rs
  src/main.rs
  tests/integration_tests/functional/test_logging.py
  vmm/src/lib.rs
  vmm/src/vmm_config/instance_info.rs
Labels: Feature: Logging, Program: Usability, Quality: Improvement

#861 Fix bad syscall handling
  CHANGELOG.md
  logger/Cargo.toml
  src/main.rs
  vmm/src/default_syscalls/x86_64.rs
  vmm/src/lib.rs
  vmm/src/sigsys_handler.rs
Labels: Priority: High, Quality: Bug

#834 Clarify getting started section of README
  README.md
Labels: Documentation: Usage

#862 Add instructions to getting-started documentation
  docs/getting-started.md
Labels: Documentation: Usage

#858 Replace sys util error with std::io::Error
  Cargo.lock
  api_server/src/request/mod.rs
  arch/Cargo.toml
  arch/src/lib.rs
  arch/src/x86_64/interrupts.rs
  arch/src/x86_64/regs.rs
  kvm/src/lib.rs
  memory_model/Cargo.toml
  memory_model/src/lib.rs
  memory_model/src/mmap.rs
  vmm/src/lib.rs
  vmm/src/vm_control.rs
  vmm/src/vmm_config/instance_info.rs
  vmm/src/vstate.rs
Labels: Program: Refactoring

#887 Fix shellcheck issues in devtool
  tools/devtool
Labels: Quality: Improvement

#863 Make EventFd non-blocking
  sys_util/src/eventfd.rs
Labels: Program: Architecture
