Repository firecracker-microvm/firecracker, pull requests merged in 2019-02, with the labels that each got.

#893 virtio-blk flush and bound checks
  CHANGELOG.md
  devices/src/lib.rs
  devices/src/virtio/block.rs
Labels: Feature: IO Virtualization, Quality: Improvement

#902 [RFC] Adaptive coverage threshold based on assisted dilligence
  tests/integration_tests/build/test_coverage.py
Labels: Priority: High, Quality: Automated Testing, Quality: CI

#909 fix logger issue
  logger/src/lib.rs
Labels: Quality: Automated Testing, Quality: Bug, Quality: CI

#907 [RFC] New API action: SendCtrlAltDel
  CHANGELOG.md
  api_server/src/request/actions.rs
  api_server/swagger/firecracker.yaml
  devices/src/legacy/i8042.rs
  devices/src/legacy/mod.rs
  docs/api_requests/actions.md
  tests/integration_tests/functional/test_api.py
  vmm/src/device_manager/legacy.rs
  vmm/src/lib.rs
  vmm/src/vstate.rs
Labels: Feature: Core Virtualization, Quality: Improvement

#926 Fix assert on the acutual http code
  tests/framework/http.py
  tests/framework/microvm.py
  tests/integration_tests/functional/test_api.py
  tests/integration_tests/functional/test_drives.py
  tests/integration_tests/functional/test_logging.py
  tests/integration_tests/functional/test_mmds.py
  tests/integration_tests/performance/test_boottime.py
  tests/integration_tests/performance/test_process_startup_time.py
Labels: Quality: Automated Testing, Quality: CI, Quality: Improvement

#924 improve jailer startup time
  jailer/src/lib.rs
  tests/integration_tests/build/test_coverage.py
Labels: Quality: Bug

#929 Added guest MAC spoofing detection
  CHANGELOG.md
  devices/src/virtio/net.rs
  logger/src/metrics.rs
Labels: Feature: Metrics, Quality: Improvement

#859 cpuid crate refactoring - part 1
  cpuid/src/bit_helper.rs
  cpuid/src/cpu_leaf.rs
  cpuid/src/lib.rs
Labels: Codebase: Refactoring, Feature: CPU Support: AMD

#910 devtool prepare_release: fix for macOS/BSD
  tools/devtool
  tools/update-credits.sh
Labels: Codebase: Build System

#947 add documentation for BitRangeExt
  cpuid/src/bit_helper.rs
  cpuid/src/lib.rs
  dumbo/src/lib.rs
  kvm/src/lib.rs
  logger/src/lib.rs
  memory_model/src/lib.rs
  micro_http/src/lib.rs
  rate_limiter/src/lib.rs
  seccomp/src/lib.rs
  vmm/src/lib.rs
Labels: Priority: High

#900 correct the comment of min_len() function
  micro_http/src/request.rs
Labels: Documentation: Code

#872 remove memory dependency for arch_gen
  Cargo.lock
  arch/src/x86_64/mod.rs
  arch/src/x86_64/mptable.rs
  arch_gen/Cargo.toml
  arch_gen/src/lib.rs
  arch_gen/src/x86/mod.rs
Labels: Feature: CPU Support: ARM, Quality: Improvement

#937 Net IO performance optimization
  devices/src/virtio/net.rs
Labels: Performance: IO
