Repository firecracker-microvm/firecracker, pull requests merged in 2019-09, with the labels that each got.

#1241 test_coverage: disambiguate the message failure
  tests/integration_tests/build/test_coverage.py
Labels: Quality: CI

#1270 net_gen: move away code that is not bindgen'd
  Cargo.lock
  net_gen/Cargo.toml
  net_gen/src/lib.rs
  net_util/src/lib.rs
  net_util/src/tap.rs
Labels: Quality: Improvement, Quality: Technical Debt

#1263 Doc for public facing content in arch crate
  api_server/src/request/mod.rs
  arch/src/aarch64/fdt.rs
  arch/src/aarch64/gic.rs
  arch/src/aarch64/mod.rs
  arch/src/aarch64/regs.rs
  arch/src/lib.rs
  arch/src/x86_64/interrupts.rs
  arch/src/x86_64/layout.rs
  arch/src/x86_64/mod.rs
  arch/src/x86_64/regs.rs
  vmm/src/lib.rs
Labels: Documentation: Code, Quality: Improvement, Quality: Technical Debt

#1274 docs: mention Ignite and swap "Beta" for "Preview"
  README.md
Labels: Documentation: Usage, Priority: Low

#1280 stdin does not return to user upon panic
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: Quality: Bug

#1255 Remove duplicated device feature detection function
  devices/src/virtio/block.rs
  devices/src/virtio/mmio.rs
  devices/src/virtio/net.rs
  devices/src/virtio/vsock/device.rs
  vmm/src/device_manager/mmio.rs
  vmm/src/lib.rs
Labels: Codebase: Refactoring, Codebase: Usability
