Repository firecracker-microvm/firecracker, pull requests merged in 2019-03, with the labels that each got.

#978 Metrics: remove `bad_syscalls`
  CHANGELOG.md
  logger/src/metrics.rs
  vmm/src/sigsys_handler.rs
Labels: Feature: Metrics, Feature: Seccomp

#983 seccomp: allow madvise(*, *, MADV_DONTNEED)
  CHANGELOG.md
  vmm/src/default_syscalls/x86_64.rs
Labels: Feature: Seccomp, Quality: Bug

#989 ARM: corectly place x86_64 specific error
  api_server/src/request/mod.rs
  arch/src/lib.rs
  arch/src/x86_64/mod.rs
  vmm/src/vstate.rs
Labels: Feature: CPU Support: ARM

#904 devtool: add command to create release tag
  CHANGELOG.md
  tools/devtool
Labels: Priority: High, Quality: Improvement

#1005 docs: rootfs and kernel image creation guide
  FAQ.md
  docs/rootfs-and-kernel-setup.md
Labels: Documentation: Usage

#991 arm64: added memory layout representation
  arch/src/aarch64/layout.rs
  arch/src/aarch64/mod.rs
Labels: Feature: CPU Support: ARM

#990 x86_64: fix inconsistent registry setup
  arch/src/x86_64/regs.rs
  vmm/src/vstate.rs
Labels: Codebase: Refactoring, Feature: CPU Support: ARM

#956 cpuid crate refactoring - part 2
  cpuid/src/bit_helper.rs
  cpuid/src/brand_string.rs
  cpuid/src/cpu_leaf.rs
  cpuid/src/lib.rs
  cpuid/src/template/c3.rs
  cpuid/src/template/mod.rs
  cpuid/src/template/t2.rs
  cpuid/src/transformer/common.rs
  cpuid/src/transformer/intel.rs
  cpuid/src/transformer/mod.rs
  tests/integration_tests/build/test_coverage.py
  vmm/src/vstate.rs
Labels: Codebase: Refactoring, Feature: CPU Support: AMD, Priority: High

#1026 implement basic cpuid filtering for AMD
  cpuid/src/cpu_leaf.rs
  cpuid/src/transformer/amd.rs
  cpuid/src/transformer/common.rs
  cpuid/src/transformer/intel.rs
Labels: Feature: CPU Support: AMD

#940 Add local macOS VM dev machine setup instructions
  docs/dev-machine-setup.md
Labels: Documentation: Usage, Priority: Low

#1030 fix AMD boot warning
  cpuid/src/cpu_leaf.rs
  cpuid/src/transformer/amd.rs
Labels: Feature: CPU Support: AMD

#1032 add support for AMD brand string
  cpuid/src/brand_string.rs
  cpuid/src/lib.rs
  cpuid/src/transformer/amd.rs
  cpuid/src/transformer/common.rs
  cpuid/src/transformer/intel.rs
  cpuid/src/transformer/mod.rs
  tests/integration_tests/functional/test_cpu_features.py
Labels: Feature: CPU Support: AMD
