Repository firecracker-microvm/firecracker, pull requests merged in 2019-04, with the labels that each got.

#891 kernel-config: Remove kernel modules from config
  resources/microvm-kernel-config
Labels: Feature: Guest OS

#1051 aarch64: setup the interrupt controller (GIC)
  arch/src/aarch64/gic.rs
  arch/src/aarch64/layout.rs
  arch/src/aarch64/mod.rs
  arch/src/aarch64/regs.rs
  vmm/src/lib.rs
  vmm/src/vstate.rs
Labels: Feature: CPU Support: ARM

#1043 update test_setup_sregs
  arch/src/x86_64/regs.rs
Labels: Feature: CPU Support: AMD

#1059 aarch64: add vcpu configuration
  arch/src/aarch64/layout.rs
  arch/src/aarch64/mod.rs
  arch/src/aarch64/regs.rs
  kernel/src/loader/mod.rs
  vmm/src/lib.rs
  vmm/src/vstate.rs
Labels: Feature: CPU Support: ARM
