Repository firecracker-microvm/firecracker, pull requests merged in 2019-08, with the labels that each got.

#1200 README update in integration tests
  CHANGELOG.md
  tests/README.md
Labels: Documentation: Usage

#1230 devtool: create cargo git registry dir if missing
  tools/devtool
Labels: Quality: Bug

#1224 repo: expand PR template with checklist
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
Labels: Contribute: Mechanics
