Repository firecracker-microvm/firecracker, pull requests merged in 2020-11, with the labels that each got.

#1883 Device-API functionality matrix & docs: fix code format
  docs/device-api.md
Labels: Status: Reviewer

#2266 charter: updated tenets
  CHARTER.md
Labels: Documentation: Charter

#2262 CI: enable snapshot related tests
  tests/integration_tests/functional/test_balloon.py
Labels: Feature: CPU Support: ARM

#2190 Return error when setting CPU template on aarch64
  src/api_server/src/parsed_request.rs
  src/api_server/src/request/machine_configuration.rs
  tests/integration_tests/functional/test_api.py
Labels: Feature: CPU Support: ARM, Status: Author

#2264 Avoid hard-coded sleep() calls in balloon driver functional tests
  tests/integration_tests/functional/test_balloon.py
Labels: Status: Reviewer

#2275 CI: add RTC test on aarch64
  tests/integration_tests/functional/test_rtc.py
Labels: Feature: CPU Support: ARM

#2277 [Balloon] Add integration test for memory scrubbing
  tests/host_tools/readmem.c
  tests/integration_tests/functional/test_balloon.py
Labels: Status: Author

#2281 Added warning comments for version bumping
  src/devices/src/virtio/balloon/persist.rs
  src/devices/src/virtio/block/persist.rs
  src/devices/src/virtio/net/persist.rs
  src/devices/src/virtio/persist.rs
  src/devices/src/virtio/vsock/persist.rs
  src/mmds/src/persist.rs
  src/rate_limiter/src/persist.rs
  src/vmm/src/device_manager/mmio.rs
  src/vmm/src/device_manager/persist.rs
  src/vmm/src/memory_snapshot.rs
  src/vmm/src/persist.rs
  src/vmm/src/vstate/vcpu/x86_64.rs
  src/vmm/src/vstate/vm.rs
Labels: Status: Author, Status: Reviewer

#2303 CI: enable partuuid test on aarch64
  tests/integration_tests/functional/test_drives.py
Labels: Status: Reviewer

#2284 Fixed function naming in mmio device registration
  src/vmm/src/builder.rs
  src/vmm/src/device_manager/mmio.rs
  src/vmm/src/device_manager/persist.rs
Labels: Status: Author

#2307 micro-http: explicit HUP/ERR handling in server
  src/micro_http/src/connection.rs
  src/micro_http/src/server.rs
Labels: Quality: Bug
