Repository firecracker-microvm/firecracker, pull requests merged in 2020-05, with the labels that each got.

#1837 dumbo: add support for TCP payloads larger than MSS
  src/dumbo/src/pdu/tcp.rs
  src/dumbo/src/tcp/connection.rs
  src/dumbo/src/tcp/endpoint.rs
  tests/integration_tests/build/test_coverage.py
  tests/integration_tests/functional/test_mmds.py
Labels: Status: Reviewer

#1839 vmm: fix rust integration tests
  src/vmm/tests/integration_tests.rs
  src/vmm/tests/mock_resources/mod.rs
  src/vmm/tests/mock_seccomp/mod.rs
  src/vmm/tests/test_utils/mod.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#1807 jailer: ensure correct permissions on folders inside jail
  CHANGELOG.md
  src/jailer/src/env.rs
  src/jailer/src/main.rs
  tests/integration_tests/build/test_coverage.py
  tests/integration_tests/security/test_jail.py
Labels: Status: Reviewer

#1740 Add descriptive error messages to unwrap()s
  src/api_server/src/lib.rs
  src/api_server/src/parsed_request.rs
  src/api_server/src/request/drive.rs
  src/devices/src/legacy/rtc_pl031.rs
  src/devices/src/virtio/mmio.rs
  src/firecracker/src/api_server_adapter.rs
  src/firecracker/src/main.rs
  src/jailer/src/env.rs
  src/mmds/src/lib.rs
  src/polly/src/event_manager.rs
  src/utils/src/net/tap.rs
  src/utils/src/time.rs
  src/vmm/src/builder.rs
  src/vmm/src/device_manager/legacy.rs
  src/vmm/src/device_manager/mmio.rs
  src/vmm/src/resources.rs
  src/vmm/src/rpc_interface.rs
  src/vmm/src/vmm_config/drive.rs
  src/vmm/src/vmm_config/net.rs
  src/vmm/src/vstate.rs
Labels: Status: Author, Status: Reviewer

#1833 tests: add test to ensure rust test scope
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#1882 [RFC] 1881: Alphabetize API definition file
  src/api_server/swagger/firecracker.yaml
Labels: Status: Reviewer

#1872 docs: mmds: remove mmds payload limitation
  docs/mmds/mmds-design.md
Labels: Status: Author

#1861 Improve `--help` content in both firecracker and jailer
  src/firecracker/src/main.rs
  src/utils/src/arg_parser.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#1794 Add DNS and config file help to network-setup.md
  docs/network-setup.md
Labels: Status: Author

#1842 Remove dependency of `utils` crate on `dumbo` crate
  Cargo.lock
  src/utils/Cargo.toml
  src/utils/src/net/tap.rs
Labels: Status: Reviewer

#1898 tests: fix net rate limiters test
  tests/integration_tests/functional/test_rate_limiter.py
Labels: Status: Reviewer

#1925 CI: adjust coverage on AMD
  tests/integration_tests/build/test_coverage.py
Labels: Feature: CPU Support: AMD

#1927 devtool: support for new parameter
  tools/devtool
Labels: Quality: CI

#1889 api_server: normalize ParsedRequest enum size
  src/api_server/src/lib.rs
  src/api_server/src/parsed_request.rs
  src/api_server/src/request/actions.rs
  src/api_server/src/request/boot_source.rs
  src/api_server/src/request/drive.rs
  src/api_server/src/request/instance_info.rs
  src/api_server/src/request/logger.rs
  src/api_server/src/request/machine_configuration.rs
  src/api_server/src/request/metrics.rs
  src/api_server/src/request/mmds.rs
  src/api_server/src/request/mod.rs
  src/api_server/src/request/net.rs
  src/api_server/src/request/snapshot.rs
  src/api_server/src/request/vsock.rs
Labels: Status: Reviewer

#1934 CI: fix bug in getting AMD's coverage
  tests/host_tools/proc.py
  tests/integration_tests/build/test_coverage.py
Labels: Quality: Bug, Quality: CI, Status: Reviewer

#1862 Improve command-line arguments
  src/jailer/src/env.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Author
