Repository firecracker-microvm/firecracker, pull requests merged in 2020-04, with the labels that each got.

#1733 Update kernel configs
  resources/microvm-kernel-arm64.config
  resources/microvm-kernel-x86_64.config
Labels: Status: Reviewer

#1745 docs: guide for updating dev container image
  CHANGELOG.md
  docs/devctr-image.md
Labels: Status: Reviewer

#1742 test_logging: removed log_file_contains_strings
  tests/integration_tests/functional/test_logging.py
Labels: Quality: Improvement, Status: Reviewer

#1741 devices: refactor test function `bus_insert`
  src/devices/src/bus.rs
Labels: Status: Reviewer

#1753 Clean up vcpu threads created by tests
  src/vmm/src/vstate.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#1656 vsock: Use TempFile when generating file names
  src/devices/src/virtio/vsock/unix/muxer.rs
Labels: Status: Author

#1757 Define trait Persist: interface for saving/restoring a component from state
  src/snapshot/src/lib.rs
  src/snapshot/src/persist.rs
Labels: Status: Reviewer

#1657 tests: Log all commands through custom endpoint
  tests/conftest.py
  tests/framework/jailer.py
  tests/framework/microvm.py
  tests/framework/utils.py
  tests/host_tools/cargo_build.py
  tests/host_tools/drive.py
  tests/host_tools/memory.py
  tests/host_tools/network.py
  tests/integration_tests/build/test_coverage.py
  tests/integration_tests/build/test_style.py
  tests/integration_tests/functional/test_cpu_features.py
  tests/integration_tests/functional/test_drives.py
  tests/integration_tests/functional/test_max_vcpus.py
  tests/integration_tests/functional/test_mmds.py
  tests/integration_tests/functional/test_rate_limiter.py
  tests/integration_tests/functional/test_shut_down.py
  tests/integration_tests/functional/test_signals.py
  tests/integration_tests/security/test_sec_audit.py
  tests/integration_tests/security/test_seccomp.py
Labels: Status: Reviewer

#1749 Implement serialization for RateLimiter
  Cargo.lock
  src/rate_limiter/Cargo.toml
  src/rate_limiter/src/lib.rs
  src/rate_limiter/src/persist.rs
Labels: Feature: Snapshotting, Status: Reviewer

#1746 Add tests for hardcoded snapshot deserialization
  src/snapshot/src/lib.rs
  src/snapshot/tests/test.rs
  src/versionize/src/primitives.rs
  src/versionize/tests/test.rs
Labels: Status: Reviewer

#1789 vmm: unify VmmController with RuntimeApiController
  src/firecracker/src/api_server_adapter.rs
  src/vmm/src/controller.rs
  src/vmm/src/lib.rs
  src/vmm/src/rpc_interface.rs
Labels: Status: Reviewer

#1785 Implement Vsock Device serialization
  src/devices/src/lib.rs
  src/devices/src/virtio/queue.rs
  src/devices/src/virtio/vsock/device.rs
  src/devices/src/virtio/vsock/mod.rs
  src/devices/src/virtio/vsock/persist.rs
  src/devices/src/virtio/vsock/unix/muxer.rs
  src/snapshot/src/lib.rs
  src/snapshot/tests/test.rs
  src/versionize/src/lib.rs
  src/versionize/src/primitives.rs
  src/versionize/tests/test.rs
  src/versionize_derive/src/descriptors/enum_desc.rs
Labels: Feature: Snapshotting

#1790 mmds: IPv4 address link-local check at config time
  CHANGELOG.md
  docs/mmds.md
  src/api_server/src/parsed_request.rs
  src/api_server/src/request/mmds.rs
  src/dumbo/src/ns.rs
  src/utils/src/net/ipv4addr.rs
  src/utils/src/net/mod.rs
  src/vmm/src/resources.rs
  src/vmm/src/rpc_interface.rs
  src/vmm/src/vmm_config/mmds.rs
  tests/integration_tests/build/test_coverage.py
  tests/integration_tests/functional/test_mmds.py
Labels: Status: Reviewer

#1795 versionize: add more unit tests
  src/snapshot/src/lib.rs
  src/snapshot/tests/test.rs
  src/versionize/src/primitives.rs
  src/versionize/tests/test.rs
Labels: Status: Reviewer

#1756 docs: add network performance numbers
  SPECIFICATION.md
  docs/network-performance.md
Labels: Status: Reviewer

#1817 devtool: log UTC timestamp at start of test
  tools/devtool
Labels: Status: Reviewer

#1815 tests: rate limiting: omit first 2s of traffic
  tests/integration_tests/functional/test_rate_limiter.py
Labels: Status: Reviewer

#1832 Fix unit test coverage for the cpuid crate
  src/cpuid/src/transformer/amd.rs
  src/cpuid/src/transformer/common.rs
  src/cpuid/src/transformer/intel.rs
  src/cpuid/src/transformer/mod.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Author
