Repository firecracker-microvm/firecracker, pull requests merged in 2020-06, with the labels that each got.

#1940 jailer: increase code coverage
  src/jailer/src/env.rs
  src/jailer/src/main.rs
  tests/integration_tests/build/test_binary_size.py
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#1958 aarch64: fix definition of DRAM_MEM_END in layout.rs
  src/arch/src/aarch64/layout.rs
Labels: Feature: CPU Support: ARM, Quality: Bug, Status: Reviewer

#1890 Snapshotting support doc
  docs/snapshotting/snapshot-support.md
  src/api_server/swagger/firecracker.yaml
Labels: Status: Reviewer

#1957 devtool: strip release binaries out of debug info
  CHANGELOG.md
  tests/host_tools/cargo_build.py
  tests/integration_tests/build/test_binary_size.py
  tools/devtool
Labels: Quality: Improvement, Status: Reviewer

#1978 clean up whitespace in "getting started" scripts
  docs/getting-started.md
Labels: Status: Reviewer
