Repository firecracker-microvm/firecracker, pull requests merged in 2020-12, with the labels that each got.

#2309 Add a short guide to using initrd_path
  docs/initrd.md
Labels: Status: Reviewer

#2310 CI: enable kcov on aarch64
  tests/integration_tests/build/test_coverage.py
Labels: Feature: CPU Support: ARM, Status: Reviewer

#2274 Change visibility of pub fun in api_server crate
  src/api_server/src/lib.rs
  src/api_server/src/parsed_request.rs
  src/api_server/src/request/actions.rs
  src/api_server/src/request/balloon.rs
  src/api_server/src/request/boot_source.rs
  src/api_server/src/request/drive.rs
  src/api_server/src/request/instance_info.rs
  src/api_server/src/request/logger.rs
  src/api_server/src/request/machine_configuration.rs
  src/api_server/src/request/metrics.rs
  src/api_server/src/request/mmds.rs
  src/api_server/src/request/net.rs
  src/api_server/src/request/snapshot.rs
  src/api_server/src/request/vsock.rs
Labels: Status: Author, Status: Reviewer

#2288 [Balloon] Update public documentation
  docs/ballooning.md
Labels: Feature: Ballooning

#2324 Add snapshot load latency baseline for v0.24.0
  tests/integration_tests/performance/test_snapshot_perf.py
Labels: Status: Reviewer

#2335 Improved snapshot creation performance tests
  tests/framework/artifacts.py
  tests/integration_tests/performance/test_snapshot_perf.py
Labels: NextRelease, Status: Author

#2347 LoadSnapshot: Implement microvm state sanity checks.
  src/vmm/src/persist.rs
  src/vmm/tests/integration_tests.rs
Labels: NextRelease, Status: Reviewer

#2292 Enabled describeInstance to show VM pause/resume
  CHANGELOG.md
  src/api_server/src/lib.rs
  src/api_server/swagger/firecracker.yaml
  src/firecracker/src/api_server_adapter.rs
  src/firecracker/src/main.rs
  src/vmm/src/resources.rs
  src/vmm/src/rpc_interface.rs
  src/vmm/src/vmm_config/instance_info.rs
  src/vmm/src/vmm_config/logger.rs
  tests/framework/microvm.py
Labels: NextRelease, Status: Reviewer

#2358 balloon: fix possible loop in inflation process
  src/devices/src/virtio/balloon/device.rs
  tests/integration_tests/build/test_coverage.py
Labels: Feature: Ballooning, NextRelease, Status: Reviewer

#2354 [ARM] enable snapshot performance tests
  tests/integration_tests/performance/test_snapshot_perf.py
Labels: Feature: CPU Support: ARM, NextRelease

#2345 Clarify support for LE CPUs only in README
  README.md
Labels: NextRelease, Status: Reviewer

#2366 CI: ignore snapshot related tests on AMD
  tests/conftest.py
Labels: Feature: CPU Support: AMD

#2367 [aarch64][snap] update ICC regs state
  src/arch/src/aarch64/gic/mod.rs
  src/arch/src/aarch64/gic/regs/icc_regs.rs
  tests/integration_tests/build/test_coverage.py
Labels: Feature: CPU Support: ARM, NextRelease

#2352 Add thread name to logger prefix.
  src/logger/src/logger.rs
  tests/integration_tests/functional/test_logging.py
Labels: Status: Author

#2368 Added example usage for merging diff snaps in docs
  docs/snapshotting/snapshot-support.md
Labels: NextRelease

#2369 Updated prod-host-setup.md with serial device recommendations
  docs/prod-host-setup.md
Labels: NextRelease

#2371 re-enable test_older_snapshot_resume_latency for aarch64
  tests/integration_tests/performance/test_snapshot_perf.py
Labels: Feature: CPU Support: ARM, NextRelease

#2370 docs: randomness handling when restoring multiple VM clones from same snapshot
  docs/snapshotting/random-for-clones.md
  docs/snapshotting/snapshot-support.md
Labels: NextRelease

#2385 docs: mention virtualization design decision for ARM
  docs/prod-host-setup.md
Labels: Feature: CPU Support: ARM, NextRelease

#2395 doc: adjusted download flow to new release model
  docs/getting-started.md
Labels: Status: Reviewer
