Repository firecracker-microvm/firecracker, pull requests merged in 2020-10, with the labels that each got.

#2146 Fix superseded advice about region choice for EC2 bare metal
  docs/dev-machine-setup.md
Labels: Status: Reviewer

#2169 arm: fix possible load-load data inconsistency
  src/devices/src/virtio/queue.rs
Labels: Status: Reviewer

#2192 docs update: seccomp is enabled by Firecracker
  docs/design.md
  docs/prod-host-setup.md
Labels: Status: Reviewer

#2200 Update Specification for v0.23.0
  SPECIFICATION.md
Labels: Status: Reviewer

#2206 v0.23.0 docs: update FAQ with supported CPUs.
  FAQ.md
Labels: Status: Reviewer

#2138 docs: add documentation on snapshot uniqueness
  docs/snapshotting/snapshot-support.md
Labels: Documentation: Usage, Status: Author

#2224 Release v0.23.0
  .mailmap
  CHANGELOG.md
  CREDITS.md
  src/api_server/swagger/firecracker.yaml
  src/firecracker/Cargo.toml
  src/jailer/Cargo.toml
Labels: Status: Reviewer

#2243 CI: disable kcov test on arm
  tests/integration_tests/build/test_coverage.py
Labels: Feature: CPU Support: ARM
