Repository firecracker-microvm/firecracker, pull requests merged in 2020-02, with the labels that each got.

#1567 logger: increase metrics count if lock poisoned.
  src/logger/src/lib.rs
Labels: Status: Author, Status: Reviewer

#1574 vmm: relax resume_vcpus's timeout
  src/vmm/src/lib.rs
Labels: Status: Reviewer

#1581 micro_http: update unit test
  src/micro_http/src/request.rs
Labels: Status: Author

#1584 provide guidelines for avoiding CVE-2019-3016
  docs/prod-host-setup.md
Labels: Status: Reviewer

#1593 [GuestMemoryMmap] rename new() to from_ranges()
  src/arch/src/aarch64/fdt.rs
  src/arch/src/aarch64/mod.rs
  src/arch/src/aarch64/regs.rs
  src/arch/src/x86_64/mod.rs
  src/arch/src/x86_64/mptable.rs
  src/arch/src/x86_64/regs.rs
  src/devices/src/virtio/block.rs
  src/devices/src/virtio/mmio.rs
  src/devices/src/virtio/net.rs
  src/devices/src/virtio/queue.rs
  src/devices/src/virtio/vsock/epoll_handler.rs
  src/devices/src/virtio/vsock/mod.rs
  src/kernel/src/loader/mod.rs
  src/vm-memory/src/guest_memory.rs
  src/vmm/src/device_manager/mmio.rs
  src/vmm/src/lib.rs
  src/vmm/src/vstate.rs
Labels: Status: Author, Status: Reviewer

#1565 Update the block device tests
  Cargo.lock
  src/devices/Cargo.toml
  src/devices/src/virtio/block/device.rs
  src/devices/src/virtio/block/request.rs
  src/devices/src/virtio/queue.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#1591 tests: Return when pytest is in discovery mode
  tests/framework/scheduler.py
Labels: Status: Author, Status: Reviewer

#1561 fix initrd FAQ section
  FAQ.md
Labels: Status: Reviewer

#1576 Add support for saving and resuming x86_64 vm and vcpu states
  src/arch/src/x86_64/msr.rs
  src/vmm/src/error.rs
  src/vmm/src/lib.rs
  src/vmm/src/vstate.rs
  tests/integration_tests/build/test_coverage.py
Labels: Feature: Snapshotting, Status: Reviewer

#1594 tests: refactor batch assignment mechanism
  tests/framework/scheduler.py
Labels: Status: Reviewer

#1589 Raise coverage for vmm builder
  src/devices/src/virtio/vsock/unix/muxer.rs
  src/vmm/src/builder.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Author, Status: Reviewer

#1616 devtool: log the errors reported by docker checks
  tools/devtool
Labels: Status: Reviewer

#1630 tests: Retry 'ps' call if PID does not show up
  tests/integration_tests/functional/test_cmd_line_start.py
Labels: Status: Reviewer
