Repository firecracker-microvm/firecracker, pull requests merged in 2020-01, with the labels that each got.

#1476 Remove usage of deprecated Error::description
  src/logger/src/error.rs
  src/logger/src/lib.rs
Labels: Status: Reviewer

#1483 FAQ: Document 'Resource busy' error in FAQ
  FAQ.md
Labels: Status: Reviewer

#1485 api_server: improve termination message
  src/api_server/src/lib.rs
Labels: Status: Reviewer

#1487 docs: mention additional logger info
  docs/api_requests/logger.md
Labels: Status: Reviewer

#1491 Remove `--seccomp-level` argument from jailer parameters
  CHANGELOG.md
  docs/jailer.md
  docs/prod-host-setup.md
  src/jailer/src/env.rs
  src/jailer/src/main.rs
  tests/framework/jailer.py
Labels: Status: Reviewer

#1465 Added binary size test
  tests/integration_tests/build/test_binary_size.py
Labels: Status: Author, Status: Reviewer

#1505 tests: fixed exit code regression
  tests/framework/scheduler.py
Labels: Quality: Automated Testing, Quality: Bug

#1507 docs: fix inconsistent reference to rootfs.ext4
  docs/rootfs-and-kernel-setup.md
Labels: Status: Reviewer

#1508 block: propagate GetFileMetadata error
  src/devices/src/virtio/block.rs
Labels: Status: Reviewer

#1509 tests: solved unit/coverage conflict
  tests/framework/scheduler.py
Labels: Quality: Automated Testing, Quality: Bug

#1407 Byteorder remove from device and dumbo crates
  Cargo.lock
  src/arch/Cargo.toml
  src/arch/src/lib.rs
  src/arch/src/x86_64/interrupts.rs
  src/devices/Cargo.toml
  src/devices/src/legacy/rtc_pl031.rs
  src/devices/src/lib.rs
  src/devices/src/virtio/mmio.rs
  src/devices/src/virtio/vsock/device.rs
  src/devices/src/virtio/vsock/packet.rs
  src/dumbo/Cargo.toml
  src/dumbo/src/lib.rs
  src/dumbo/src/pdu/bytes.rs
  src/utils/src/byte_order.rs
  src/utils/src/lib.rs
Labels: Status: Author, Status: Reviewer

#1514 tests: leftover aarch64 hardcoded syscall
  tests/integration_tests/security/demo_seccomp/Cargo.lock
  tests/integration_tests/security/demo_seccomp/Cargo.toml
  tests/integration_tests/security/demo_seccomp/src/bin/seccomp_rules/mod.rs
Labels: Quality: Bug, Status: Reviewer

#1510 arch/x86_64: add separate MSRs related module
  src/arch/src/x86_64/mod.rs
  src/arch/src/x86_64/msr.rs
  src/arch/src/x86_64/regs.rs
  src/vmm/src/vstate.rs
Labels: Status: Reviewer

#1513 [GuestMemory] rename to GuestMemoryMmap
  src/arch/src/aarch64/fdt.rs
  src/arch/src/aarch64/mod.rs
  src/arch/src/aarch64/regs.rs
  src/arch/src/x86_64/mod.rs
  src/arch/src/x86_64/mptable.rs
  src/arch/src/x86_64/regs.rs
  src/devices/src/virtio/block.rs
  src/devices/src/virtio/mmio.rs
  src/devices/src/virtio/net.rs
  src/devices/src/virtio/queue.rs
  src/devices/src/virtio/vsock/csm/connection.rs
  src/devices/src/virtio/vsock/device.rs
  src/devices/src/virtio/vsock/epoll_handler.rs
  src/devices/src/virtio/vsock/mod.rs
  src/devices/src/virtio/vsock/packet.rs
  src/kernel/src/loader/mod.rs
  src/vm-memory/src/guest_memory.rs
  src/vm-memory/src/lib.rs
  src/vmm/src/device_manager/mmio.rs
  src/vmm/src/error.rs
  src/vmm/src/lib.rs
  src/vmm/src/vstate.rs
Labels: Status: Reviewer

#1506 tests: fix broken parameter propagation
  tests/framework/jailer.py
  tests/framework/microvm.py
  tests/integration_tests/functional/test_cmd_line_start.py
Labels: Status: Reviewer

#1542 Remove RescanBlockDevice from the /actions API
  CHANGELOG.md
  docs/api_requests/actions.md
  docs/api_requests/patch-block.md
  src/api_server/src/lib.rs
  src/api_server/src/parsed_request.rs
  src/api_server/src/request/actions.rs
  src/api_server/swagger/firecracker.yaml
  src/devices/src/virtio/block.rs
  src/firecracker/src/main.rs
  src/vmm/src/error.rs
  src/vmm/src/lib.rs
  tests/integration_tests/functional/test_api.py
  tests/integration_tests/functional/test_drives.py
Labels: Status: Reviewer

#1495 Renamed `region_end` to `last_addr` in guest memory
  src/arch/src/aarch64/fdt.rs
  src/arch/src/aarch64/mod.rs
  src/arch/src/x86_64/mod.rs
  src/devices/src/virtio/block.rs
  src/kernel/src/loader/mod.rs
  src/vm-memory/src/guest_memory.rs
Labels: Status: Reviewer

#1497 Reworked checked_range_offset and get_host_address
  src/devices/src/virtio/queue.rs
  src/devices/src/virtio/vsock/packet.rs
  src/vm-memory/src/guest_memory.rs
Labels: Status: Author

#1549 micro_http: some doc and code corrections
  src/micro_http/src/common/headers.rs
  src/micro_http/src/common/mod.rs
  src/micro_http/src/connection.rs
  src/micro_http/src/request.rs
  src/micro_http/src/response.rs
  src/micro_http/src/server.rs
Labels: Status: Author
