Repository firecracker-microvm/firecracker, pull requests merged in 2020-08, with the labels that each got.

#2055 Improved error handling for rate limiter
  src/rate_limiter/src/persist.rs
Labels: Status: Author

#2080 upgrade vm-memory version to 0.2.2
  Cargo.lock
  src/arch/Cargo.toml
  src/devices/Cargo.toml
  src/kernel/Cargo.toml
  src/vmm/Cargo.toml
Labels: Status: Reviewer

#2074 vmm: use display trait in errors where possible
  src/vmm/src/lib.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#2056 issue_templates: Add bug and feature request templates.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Status: Reviewer

#2084 Improved virtqueue error handling for used ring
  src/devices/src/lib.rs
  src/devices/src/virtio/block/device.rs
  src/devices/src/virtio/net/device.rs
  src/devices/src/virtio/queue.rs
  src/devices/src/virtio/vsock/device.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#2087 security: renamed the policy file to security.md
  CHANGELOG.md
  README.md
  SECURITY.md
Labels: Status: Reviewer

#2061 Improve firecracker --version output
  CHANGELOG.md
  build.rs
  src/firecracker/Cargo.toml
  src/firecracker/src/main.rs
  src/jailer/Cargo.toml
  src/jailer/src/main.rs
  tools/devctr/Dockerfile.aarch64
  tools/devctr/Dockerfile.x86_64
  tools/devtool
Labels: Status: Reviewer

#2085 Improve snapshot load error handling.
  src/snapshot/src/lib.rs
  src/snapshot/tests/test.rs
Labels: Feature: Snapshotting, Quality: Improvement, Status: Reviewer

#2081 vmm: refactor vcpu.rs file
  src/vmm/src/builder.rs
  src/vmm/src/lib.rs
  src/vmm/src/persist.rs
  src/vmm/src/vstate/vcpu.rs
  src/vmm/src/vstate/vcpu/aarch64.rs
  src/vmm/src/vstate/vcpu/mod.rs
  src/vmm/src/vstate/vcpu/x86_64.rs
  src/vmm/src/vstate/vm.rs
  tests/integration_tests/build/test_coverage.py
Labels: Feature: CPU Support: ARM, Status: Reviewer

#2073 Made Invalid Header error more verbose
  src/dumbo/src/tcp/endpoint.rs
  src/micro_http/src/common/headers.rs
  src/micro_http/src/common/mod.rs
  src/micro_http/src/connection.rs
  src/micro_http/src/lib.rs
  src/micro_http/src/request.rs
  src/micro_http/src/server.rs
Labels: Status: Author

#2103 Update docs to reflect experimental status of gnu builds and glibc jailer support
  README.md
  docs/getting-started.md
  docs/jailer.md
Labels: Status: Reviewer
