Repository firecracker-microvm/firecracker, pull requests merged in 2020-07, with the labels that each got.

#1988 virtio net: don't rely on vnet header always being present
  CHANGELOG.md
  src/devices/src/lib.rs
  src/devices/src/virtio/net/device.rs
  src/devices/src/virtio/net/mod.rs
  src/logger/src/metrics.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#1989 net: add metrics
  CHANGELOG.md
  src/devices/src/virtio/net/device.rs
  src/logger/src/metrics.rs
Labels: Status: Reviewer

#1813 Remove dumbo's dependency on mmds
  Cargo.lock
  src/devices/Cargo.toml
  src/devices/src/virtio/net/device.rs
  src/devices/src/virtio/net/persist.rs
  src/dumbo/Cargo.toml
  src/dumbo/src/lib.rs
  src/dumbo/src/pdu/udp.rs
  src/dumbo/src/tcp/endpoint.rs
  src/dumbo/src/tcp/handler.rs
  src/dumbo/src/tcp/mod.rs
  src/micro_http/src/response.rs
  src/mmds/Cargo.toml
  src/mmds/src/lib.rs
  src/mmds/src/ns.rs
  src/mmds/src/persist.rs
  src/vmm/src/lib.rs
  src/vmm/src/resources.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#1880 Upgrade to Versionize v0.1.1.
  Cargo.lock
  src/arch/Cargo.toml
  src/cpuid/Cargo.toml
  src/devices/Cargo.toml
  src/mmds/Cargo.toml
  src/rate_limiter/Cargo.toml
  src/snapshot/Cargo.toml
  src/vmm/Cargo.toml
Labels: Status: Author

#2020 logger: add support for case-insensitive level
  CHANGELOG.md
  src/api_server/src/request/logger.rs
  src/api_server/swagger/firecracker.yaml
  src/vmm/src/vmm_config/logger.rs
Labels: Status: Reviewer

#1911 Add snapshot versioning docs.
  docs/images/version_graph.png
  docs/images/versionize.png
  docs/snapshotting/versioning.md
Labels: Feature: Snapshotting, Status: Reviewer

#2002 Add snapshot integration tests.
  tests/framework/artifacts.py
  tests/framework/builder.py
  tests/framework/microvm.py
  tests/framework/resources.py
  tests/host_tools/network.py
  tests/host_tools/snapshot_helper.py
  tests/integration_tests/functional/test_pause_resume.py
  tests/integration_tests/functional/test_snapshot_basic.py
Labels: Status: Reviewer

#2029 aarch64: fix confusion in IRQ allocation
  src/arch/src/aarch64/gic.rs
  src/arch/src/aarch64/layout.rs
Labels: Feature: CPU Support: ARM, Quality: Improvement

#2022 block: added metrics for throttled events
  CHANGELOG.md
  src/devices/src/virtio/block/device.rs
  src/logger/src/metrics.rs
Labels: Status: Author

#1996 Switch to vmm-sys-utils epoll
  Cargo.lock
  src/devices/src/virtio/vsock/unix/muxer.rs
  src/micro_http/src/server.rs
  src/polly/src/event_manager.rs
  src/utils/Cargo.toml
  src/utils/src/epoll.rs
  src/utils/src/lib.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Author

#2038 Use syscall.rs from vmm_sys_util
  src/utils/src/lib.rs
  src/utils/src/syscall.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Author

#1985 micro-http: unsigned Content-Length + several checked arithmetic operations
  src/dumbo/src/tcp/endpoint.rs
  src/micro_http/src/common/headers.rs
  src/micro_http/src/common/mod.rs
  src/micro_http/src/connection.rs
  src/micro_http/src/request.rs
Labels: Status: Author

#2040 Use vmm_sys_util from utils everywhere
  Cargo.lock
  src/cpuid/Cargo.toml
  src/cpuid/src/lib.rs
  src/cpuid/src/transformer/common.rs
  src/cpuid/src/transformer/mod.rs
  src/utils/src/lib.rs
  src/vmm/Cargo.toml
  src/vmm/tests/integration_tests.rs
Labels: Status: Reviewer

#1921 devices: btimer: Add boot timer device.
  resources/tests/init.c
  src/arch/src/aarch64/fdt.rs
  src/arch/src/lib.rs
  src/devices/src/lib.rs
  src/devices/src/pseudo/boot_timer.rs
  src/devices/src/pseudo/mod.rs
  src/vmm/src/builder.rs
  src/vmm/src/device_manager/mmio.rs
  src/vmm/src/device_manager/persist.rs
  src/vmm/src/lib.rs
  src/vmm/src/vmm_config/logger.rs
  src/vmm/src/vstate.rs
  tests/integration_tests/build/test_coverage.py
  tests/integration_tests/build/test_style.py
  tests/integration_tests/performance/test_boottime.py
Labels: Status: Reviewer

#1825 aarch64: First patch towards VcpuState save/restore
  src/arch/src/aarch64/regs.rs
  src/vmm/src/vstate.rs
Labels: Status: Reviewer

#2030 Add snapshot performance integration test.
  tests/framework/builder.py
  tests/framework/microvm.py
  tests/integration_tests/functional/test_snapshot_basic.py
  tests/integration_tests/performance/test_snapshot_perf.py
Labels: Feature: Snapshotting, Status: Reviewer

#2053 Fix comments of copy miss
  src/logger/src/metrics.rs
Labels: Quality: Improvement

#2048 rate_limiter: enforce limit for large requests
  src/devices/src/virtio/net/device.rs
  src/rate_limiter/src/lib.rs
Labels: Status: Reviewer
