Repository firecracker-microvm/firecracker, pull requests merged in 2020-09, with the labels that each got.

#2088 x86_64/regs: improve coverage
  src/arch/src/x86_64/regs.rs
Labels: Quality: Improvement

#2097 snapshot: disable diff snapshots support
  CHANGELOG.md
  docs/snapshotting/snapshot-support.md
  src/api_server/src/lib.rs
  src/api_server/src/request/snapshot.rs
  src/api_server/swagger/firecracker.yaml
  src/vmm/src/persist.rs
  src/vmm/src/rpc_interface.rs
  src/vmm/src/vmm_config/snapshot.rs
  src/vmm/tests/integration_tests.rs
  tests/integration_tests/build/test_coverage.py
Labels: Feature: Snapshotting, Status: Reviewer

#2114 use latest versionize/versionize_derive
  Cargo.lock
  src/arch/Cargo.toml
  src/cpuid/Cargo.toml
  src/devices/Cargo.toml
  src/dumbo/Cargo.toml
  src/kernel/Cargo.toml
  src/logger/Cargo.toml
  src/micro_http/Cargo.toml
  src/mmds/Cargo.toml
  src/polly/Cargo.toml
  src/rate_limiter/Cargo.toml
  src/snapshot/Cargo.toml
  src/snapshot/src/lib.rs
  src/utils/Cargo.toml
  src/vmm/Cargo.toml
Labels: Status: Reviewer

#2118 snapshot: improve queue restore sanity checks
  src/devices/src/virtio/block/persist.rs
  src/devices/src/virtio/net/persist.rs
  src/devices/src/virtio/persist.rs
  src/devices/src/virtio/vsock/persist.rs
Labels: Feature: Snapshotting, Status: Reviewer
