Repository firecracker-microvm/firecracker, pull requests merged in 2021-12, with the labels that each got.

#2809 [feature/io_uring] Fix destructor call order
  src/io_uring/src/lib.rs
Labels: Status: Reviewer

#2817 devtool: set memlock:unlimited on container
  tools/devtool
Labels: Status: Reviewer

#2766 Improve Display of VM Resource Errors
  src/firecracker/src/main.rs
  src/vmm/src/resources.rs
  src/vmm/src/vmm_config/drive.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#2825 CI: enable snapshot tests on ARM
  tests/integration_tests/functional/test_snapshot_advanced.py
Labels: Feature: CPU Support: ARM

#2829 [feature/io_uring] Undo skipping some snapshot integration tests
  tests/framework/artifacts.py
  tests/integration_tests/functional/test_cmd_line_parameters.py
  tests/integration_tests/functional/test_snapshot_advanced.py
  tests/integration_tests/performance/test_snapshot_perf.py
Labels: Status: Reviewer

#2832 Add checksum of release archive
  CHANGELOG.md
  tools/devtool
Labels: Quality: Technical Debt
