Repository firecracker-microvm/firecracker, pull requests merged in 2021-03, with the labels that each got.

#2494 CI: fix bug in gitlint test
  tests/integration_tests/style/test_gitlint.py
Labels: Quality: Bug

#2498 [Performance tests] Fixed bug in error propagation
  tests/framework/utils.py
Labels: Quality: Bug

#2499 [Metrics] Add warning comment for race condition in metrics initialization
  src/logger/src/metrics.rs
Labels: Documentation: Code

#2504 tests: sync FS before block IO performance test
  tests/integration_tests/performance/test_block_performance.py
Labels: Status: Reviewer

#2484 Docs: Suggestion against warning message
  docs/rootfs-and-kernel-setup.md
Labels: Status: Reviewer
