Repository firecracker-microvm/firecracker, pull requests merged in 2021-01, with the labels that each got.

#2397 Updated FAQ.md
  FAQ.md
Labels: Documentation: Usage

#2380 devtool: change docker repo to ecr
  CHANGELOG.md
  docs/devctr-image.md
  tools/devtool
Labels: Status: Reviewer

#2398 Mention lack of cross-architecture emulation support in FAQ
  FAQ.md
Labels: Documentation: Design

#2404 Seccomp: allow clock_gettime with any parameters.
  src/vmm/src/default_syscalls/filters.rs
Labels: Feature: Seccomp, Quality: Bug, Status: Reviewer

#2406 api_server: add documentation for public items
  src/api_server/src/lib.rs
  src/firecracker/src/api_server_adapter.rs
Labels: Status: Reviewer

#2413 tests: fix snapshot tests for older versions
  tests/framework/artifacts.py
  tests/framework/utils.py
  tests/integration_tests/functional/test_snapshot_advanced.py
  tests/integration_tests/performance/test_snapshot_perf.py
Labels: Quality: Automated Testing, Status: Reviewer

#2421 #2418 Update KVM compatibility checks
  src/vmm/src/vstate/system.rs
Labels: Status: Reviewer

#2340 dedupe literal HTTP response and request strings
  src/api_server/src/parsed_request.rs
Labels: Status: Author

#2431 devtool: allow fetching private git repos
  .cargo/config
  CHANGELOG.md
  docs/getting-started.md
  tools/devtool
Labels: Status: Reviewer
