Repository firecracker-microvm/firecracker, pull requests merged in 2021-06, with the labels that each got.

#2578 Updated snapshot docs with ARM kernel parameter induced latency
  docs/prod-host-setup.md
Labels: Documentation: Usage

#2619 allow diff snapshots on on uVMs with vsock devices
  src/vmm/src/rpc_interface.rs
  tests/integration_tests/functional/test_api.py
  tests/integration_tests/functional/test_snapshot_basic.py
Labels: NextRelease, Status: Reviewer

#2617 prod-host-setup: recommendation on async-unsafe signal handlers
  docs/prod-host-setup.md
Labels: Status: Reviewer

#2565 Add property based test for block device Request::parse()
  src/devices/Cargo.toml
  src/devices/src/virtio/block/request.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Author, Status: Reviewer

#2633 add negative tests for mem_size in machine config
  tests/integration_tests/functional/test_api.py
Labels: Status: Reviewer

#2564 Use the evset passed as a parameter instead of the one from connection
  src/devices/src/virtio/vsock/unix/muxer.rs
Labels: Status: Reviewer
