Repository firecracker-microvm/firecracker, pull requests merged in 2021-05, with the labels that each got.

#2529 Add `describe-snapshot` parameter to fetch snapshot data version
  CHANGELOG.md
  Cargo.lock
  src/firecracker/Cargo.toml
  src/firecracker/src/main.rs
  src/snapshot/src/lib.rs
  src/utils/src/arg_parser.rs
  tests/integration_tests/build/test_coverage.py
  tests/integration_tests/functional/test_balloon.py
  tests/integration_tests/functional/test_cmd_line_parameters.py
  tests/integration_tests/functional/test_snapshot_advanced.py
  tests/integration_tests/functional/test_snapshot_basic.py
Labels: Status: Reviewer

#2541 Remove extra logic from balloon API change
  tests/framework/resources.py
  tests/integration_tests/functional/test_balloon.py
  tests/integration_tests/functional/test_snapshot_advanced.py
Labels: Quality: CI, Quality: Technical Debt, Status: Reviewer

#2569 seccomp: allow timezone-specific syscalls on all threads
  resources/seccomp/aarch64-unknown-linux-musl.json
  resources/seccomp/x86_64-unknown-linux-musl.json
Labels: Status: Reviewer

#2583 [v0.24.4] devtool: add check_ssbd() to checkenv()
  tools/devtool
Labels: Status: Reviewer

#2580 Improve reliability of Snapshot Resume latency test
  src/vmm/src/device_manager/mmio.rs
  tests/framework/builder.py
Labels: Status: Author
