Repository firecracker-microvm/firecracker, pull requests merged in 2021-08, with the labels that each got.

#2686 Avoid overflow on computing vsock packet used length
  src/devices/src/virtio/vsock/csm/connection.rs
  src/devices/src/virtio/vsock/device.rs
  src/devices/src/virtio/vsock/packet.rs
Labels: Status: Reviewer, NextRelease

#2657 missing step for aarch64
  docs/rootfs-and-kernel-setup.md
Labels: Status: Author

#2691 cargo: removed yanked crate dependencies
  Cargo.lock
Labels: NextRelease

#2698 fix intermittent block rate limiter test failure
  tests/integration_tests/functional/test_drives.py
Labels: Status: Reviewer

#2702 [block] simplify unsafe flush behavior
  src/devices/src/virtio/block/device.rs
  src/devices/src/virtio/block/request.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#2688 [docs] adds simple bridge networking documentation.
  docs/network-setup.md
Labels: Status: Reviewer

#2652 Change jailer's 'unshare' + 'exec' to 'clone'
  docs/jailer.md
  src/jailer/src/env.rs
  src/jailer/src/main.rs
Labels: Status: Reviewer
