Repository firecracker-microvm/firecracker, pull requests merged in 2022-01, with the labels that each got.

#2833 remove deprecated --seccomp-level param
  CHANGELOG.md
  src/firecracker/src/main.rs
  src/utils/src/arg_parser.rs
  src/vmm/build.rs
  src/vmm/src/seccomp_filters/mod.rs
  tests/integration_tests/security/test_custom_seccomp.py
  tests/integration_tests/security/test_seccomp.py
Labels: Status: Reviewer

#2852 CI: increase threshold for startup on ARM
  tests/integration_tests/performance/test_process_startup_time.py
Labels: Quality: CI

#2846 docs: kernel policy support
  CHANGELOG.md
  FAQ.md
  README.md
  docs/RELEASE_POLICY.md
  docs/design.md
  docs/getting-started.md
  docs/kernel-policy.md
  docs/prod-host-setup.md
  docs/rootfs-and-kernel-setup.md
Labels: NextRelease

#2866 rustfmt: format doc comments
  src/api_server/src/lib.rs
  src/cpuid/src/bit_helper.rs
  src/logger/src/logger.rs
  src/mmds/src/data_store.rs
  src/net_gen/src/iff.rs
  src/snapshot/src/lib.rs
  src/utils/src/net/ipv4addr.rs
  src/utils/src/sm.rs
  tests/integration_tests/style/test_rust.py
Labels: Quality: CI

#2868 tests: remove catch..skip statements
  tests/integration_tests/functional/test_drives.py
Labels: Status: Reviewer

#2873 mmds: compute token's expiry in ms instead of seconds
  src/mmds/src/token.rs
  src/utils/src/time.rs
Labels: NextRelease

#2863 docs: update to include MMDS V2 behavior
  CHANGELOG.md
  docs/device-api.md
  docs/mmds/mmds-design.md
  docs/mmds/mmds-user-guide.md
Labels: NextRelease

#2875 [backport][devtool] copy relase artifacts before test run
  tools/devtool
Labels: NextRelease

#2878 tests: ensure MMDS works as expected when configuring microVM from file
  tests/framework/jailer.py
  tests/framework/utils.py
  tests/framework/vm_config_with_mmdsv1.json
  tests/framework/vm_config_with_mmdsv2.json
  tests/integration_tests/functional/test_cmd_line_start.py
  tests/integration_tests/functional/test_mmds.py
Labels: Status: Reviewer, NextRelease
