Repository firecracker-microvm/firecracker, pull requests merged in 2022-10, with the labels that each got.

#3157 PR template: change relative link to absolute link
  .github/pull_request_template.md
Labels: Status: Reviewer

#3144 [snapshot-ga] Additional info added to snap state.
  src/vmm/benches/main.rs
  src/vmm/src/builder.rs
  src/vmm/src/lib.rs
  src/vmm/src/persist.rs
  src/vmm/src/rpc_interface.rs
  src/vmm/src/version_map.rs
  src/vmm/src/vmm_config/boot_source.rs
  src/vmm/src/vmm_config/machine_config.rs
  src/vmm/tests/integration_tests.rs
  tests/integration_tests/functional/test_api.py
Labels: Status: Reviewer

#3159 Backport fix for virtio queue in 1.0
  src/devices/src/virtio/block/device.rs
  src/devices/src/virtio/queue.rs
Labels: Status: Reviewer

#3160 Backport fix for virtio queue in 1.1
  src/devices/src/virtio/block/device.rs
  src/devices/src/virtio/queue.rs
Labels: Status: Reviewer

#3167 [Snapshot] Performance baselines for Intel 4.14
  tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
Labels: Performance: IO, Status: Reviewer, NextRelease

#3170 [Snapshot] Performance baselines for AMD 5.10
  tests/integration_tests/performance/configs/test_snap_restore_performance_config_5.10.json
Labels: Performance: IO, Status: Reviewer, NextRelease

#3169 arch/x86_64: save MSR_IA32_FEATURE_CONTROL
  src/arch/src/x86_64/msr.rs
Labels: Status: Reviewer

#3171 update CHANGELOG with self-DoS fix
  CHANGELOG.md
Labels: Documentation: Code, Status: Reviewer

#3181 Log kernel version and CPU in tests
  tools/devtool
Labels: Status: Reviewer

#3172 Update snapshot-for-clones doc to reseed RNG
  docs/snapshotting/random-for-clones.md
Labels: Status: Reviewer

#3192 Fix gem dependencies in docker file
  tools/devctr/Dockerfile.x86_64
Labels: Quality: Bug

#3205 Update `MAINTAINERS.md`
  MAINTAINERS.md
Labels: Status: Reviewer

#3122 Consuming linux-loader v0.7.0 for bugfix of the Cmdline
  CHANGELOG.md
  Cargo.lock
  src/arch/src/aarch64/fdt.rs
  src/arch/src/aarch64/mod.rs
  src/vm-memory/Cargo.toml
  src/vmm/src/builder.rs
  src/vmm/src/device_manager/mmio.rs
  src/vmm/src/lib.rs
  src/vmm/src/resources.rs
  src/vmm/src/vmm_config/boot_source.rs
Labels: NextRelease

#3193 Specify AWS CLI version in devctr-image.md
  docs/devctr-image.md
Labels: Documentation: Design

#3218 docs: cross kernel snapshot incompatibility on AMD
  docs/kernel-policy.md
Labels: Status: Reviewer, NextRelease

#3222 Increase serialize(no-crc) target benchmark
  tests/integration_tests/performance/test_versioned_serialization_benchmark.py
Labels: NextRelease

#3220 test: reduce snapshot size in test
  tests/integration_tests/functional/test_snapshot_basic.py
Labels: Status: Reviewer, NextRelease

#3219 Revert default behavior of cargo build
  .cargo/config
  src/vmm/build.rs
Labels: NextRelease
