Repository firecracker-microvm/firecracker, pull requests merged in 2022-07, with the labels that each got.

#3048 Fixing git hooks setup docs
  CONTRIBUTING.md
  rusty-hook.toml
Labels: Documentation: Usage

#3054 CI: intermittent spectre mitigation fail
  tests/conftest.py
  tools/devtool
Labels: Quality: Bug, Quality: CI

#3053 mmds: small doc fix
  docs/mmds/mmds-user-guide.md
Labels: Documentation: Design

#3065 docs: add details on CVE-2022-1789
  docs/prod-host-setup.md
Labels: Status: Reviewer
