Repository firecracker-microvm/firecracker, pull requests merged in 2022-04, with the labels that each got.

#2962 uffd: enable EVENT_REMOVE for ballooning
  src/vmm/src/persist.rs
Labels: Feature: UFFD

#2965 remove unused struct field `format_version` on Snapshot
  src/snapshot/src/lib.rs
  tests/integration_tests/build/test_coverage.py
Labels: Codebase: Refactoring

#2964 api_server: VmmConfig swagger definition to reflect the actual state of the API
  CHANGELOG.md
  src/api_server/swagger/firecracker.yaml
Labels: Codebase: Usability

#2971 api: fix race in api connecting logic
  src/api_server/src/lib.rs
  src/firecracker/src/api_server_adapter.rs
  tests/integration_tests/build/test_coverage.py
Labels: Quality: Bug

#2955 Using tagged enum variants for exit codes
  src/api_server/src/lib.rs
  src/firecracker/src/api_server_adapter.rs
  src/firecracker/src/main.rs
  src/vmm/benches/main.rs
  src/vmm/src/lib.rs
  src/vmm/src/rpc_interface.rs
  src/vmm/src/signal_handler.rs
  src/vmm/src/vstate/vcpu/mod.rs
  src/vmm/tests/integration_tests.rs
Labels: Codebase: Refactoring
