Repository firecracker-microvm/firecracker, pull requests merged in 2022-08, with the labels that each got.

#3078 Fix devtool build_devctr doc
  docs/devctr-image.md
  tools/devtool
Labels: Documentation: Usage

#3095 CI: enhance allowed CPU features on ARM guests
  tests/integration_tests/functional/test_cpu_features.py
Labels: Status: Reviewer

#3000 test: gather baselines for serialize bench
  tests/integration_tests/performance/test_versioned_serialization_benchmark.py
Labels: Status: Reviewer

#3107 Add details to docs on CVE-2022-26373
  docs/prod-host-setup.md
Labels: Status: Reviewer

#3087 Use IMDSv2
  tests/framework/utils_cpuid.py
  tests/framework/utils_imdsv2.py
Labels: Quality: CI, Quality: Technical Debt, Status: Reviewer
