Repository firecracker-microvm/firecracker, pull requests merged in 2022-11, with the labels that each got.

#3224 add performance baseline for m6i.metal
  CHANGELOG.md
  tests/integration_tests/performance/configs/test_block_performance_config_4.14.json
  tests/integration_tests/performance/configs/test_block_performance_config_5.10.json
  tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
  tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
  tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
  tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
  tests/integration_tests/performance/configs/test_snap_restore_performance_config_4.14.json
  tests/integration_tests/performance/configs/test_snap_restore_performance_config_5.10.json
  tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
  tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
  tools/parse_baselines/main.py
Labels: Performance: Misc

#3214 Docs: Update snapshot support doc
  docs/snapshotting/snapshot-support.md
Labels: Status: Reviewer, NextRelease

#3231 doc: fix typo in AMD kernel version: 4.15 -> 4.14
  docs/kernel-policy.md
Labels: Documentation: Code

#3183 doc: Tweak markdown formatting
  docs/jailer.md
Labels: Status: Reviewer

#3245 make tests fail when criteria not found
  tests/framework/stats/consumer.py
Labels: Quality: Automated Testing

#3253 Revert "make tests fail when criteria not found"
  tests/framework/stats/consumer.py
Labels: Performance: Misc

#3256 tests: make tests fail when baseline not found
  tests/framework/stats/criteria.py
Labels: Quality: Automated Testing

#3060 Update docs to provide better clarity of supported features
  docs/design.md
  docs/prod-host-setup.md
Labels: Documentation: Design, Status: Reviewer, NextRelease

#3272 Linking `has_cpuid` todo
  src/cpuid/src/common.rs
Labels: Status: Reviewer

#3281 test: add T2S to cross-kernel/CPU snapshot tests
  tests/integration_tests/functional/test_snapshot_restore_cross_kernel.py
  tools/create_snapshot_artifact/main.py
Labels: Quality: Automated Testing
