Repository firecracker-microvm/firecracker, pull requests merged in 2023-09, with the labels that each got.

#4087 test: add a new test to run Firecracker in popular Docker containers
  tools/test-popular-containers/build_rootfs.sh
  tools/test-popular-containers/fcnet.start
  tools/test-popular-containers/test-docker-rootfs.py
Labels: Status: Awaiting review, python

#4098 Update the MSR baseline for T2CL on Cascade Lake + kernel 4.14
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_4.14host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_4.14host_5.10guest.csv
Labels: Status: Awaiting review

#4097 [1.3][Backport] Add RUSTSEC-2023-0056 to audit.toml
  .cargo/audit.toml
Labels: Status: Awaiting review

#4100 test: add a new, more complete boottime test
  tests/integration_tests/performance/test_boottime.py
Labels: Status: Awaiting review, Type: Performance

#4101 chore: Update MSR baselines for T2CL on kernel 6.1
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_6.1host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_6.1host_5.10guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_ICELAKE_6.1host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_ICELAKE_6.1host_5.10guest.csv
Labels: Status: Awaiting review

#4103 chore: Update MSR baselines for T2CL on kernel 5.10
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_5.10host_5.10guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_ICELAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_ICELAKE_5.10host_5.10guest.csv
Labels: Status: Awaiting review

#4106 test: Only run clippy lint test with -Dwarnings
  .cargo/config
  tests/host_tools/cargo_build.py
Labels: Status: Awaiting review

#4105 test: Print error message if aws cli not available
  tools/devtool
Labels: Status: Awaiting review

#4108 Add kani proofs for `IoVecBuffer` types
  src/vmm/src/devices/virtio/iovec.rs
Labels: Status: Awaiting review

#4110 chore: update maintainers
  MAINTAINERS.md
Labels: Status: Awaiting review

#4111 chore: update maintainers
  MAINTAINERS.md
Labels: Status: Awaiting review

#4116 chore(perf): updated m6a vsock_throughput perf
  tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
  tests/integration_tests/performance/configs/test_vsock_throughput_config_6.1.json
Labels: Status: Awaiting review, Type: Performance

#4123 test: Simplify test_kani.py
  tests/integration_tests/test_kani.py
Labels: Status: Awaiting review

#4130 fix:import testing framework for few tools scripts
  tools/create_snapshot_artifact/main.py
  tools/test-popular-containers/test-docker-rootfs.py
Labels: Status: Awaiting review

#4122 snapshot: deprecate forward compatibility
  CHANGELOG.md
  docs/snapshotting/snapshot-support.md
  src/api_server/src/request/snapshot.rs
  src/api_server/swagger/firecracker.yaml
  tests/integration_tests/functional/test_api.py
Labels: Status: Awaiting review
