Repository firecracker-microvm/firecracker, pull requests merged in 2023-07, with the labels that each got.

#3934 chore: update hermit-abi
  Cargo.lock
Labels: Status: Awaiting review

#3936 Backport T2S template fix to v1.2
  CHANGELOG.md
  resources/tests/msr/msr_list_T2S_4.14.csv
  resources/tests/msr/msr_list_T2S_5.10.csv
  src/cpuid/src/template/intel/t2s.rs
Labels: Type: Fix

#3903 docs: Simplify support docs
  README.md
  docs/getting-started.md
  docs/kernel-policy.md
  docs/snapshotting/snapshot-support.md
Labels: Status: Awaiting review, Type: Documentation

#3943 chore: collect network latency baselines
  tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
  tests/integration_tests/performance/configs/test_network_latency_config_5.10.json
  tests/integration_tests/performance/configs/test_network_latency_config_6.1.json
Labels: Status: Awaiting review

#3603 Warn on `clippy::cast_possible_wrap`
  .cargo/config
  src/jailer/src/resource_limits.rs
  src/logger/src/metrics.rs
  src/utils/src/byte_order.rs
  src/utils/src/time.rs
  src/utils/src/vm_memory.rs
  src/vmm/src/arch/x86_64/interrupts.rs
  src/vmm/src/arch/x86_64/mptable.rs
  src/vmm/src/devices/virtio/net/device.rs
  src/vmm/src/devices/virtio/net/tap.rs
  src/vmm/src/io_uring/mod.rs
  src/vmm/src/io_uring/operation/mod.rs
  src/vmm/src/vstate/system.rs
Labels: Priority: Low, Status: Awaiting review, Type: Fix

#3954 chore: Update vsock throughput baseline for m6a.metal + kernel 4.14
  tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
Labels: Status: Awaiting review

#3959 refactor: Improving code debugability
  src/firecracker/src/api_server_adapter.rs
  src/firecracker/src/main.rs
  src/vmm/src/rpc_interface.rs
Labels: Priority: Low

#3961 fix(vmm): Disable SVM on T2A template
  CHANGELOG.md
  resources/tests/static_cpu_templates/t2a.json
  src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2a.rs
Labels: Status: Awaiting review, Type: Fix

#3964 fix: Comment in dockerfile breaking cargo build
  tools/devctr/Dockerfile
  tools/devtool
Labels: Status: Awaiting review

#3963 test: Add retries to get firecracker PID in new ns
  tests/framework/microvm.py
  tests/integration_tests/security/test_jail.py
Labels: Status: Awaiting review, Type: Fix

#3965 test: refactor test_rate_limiter.py
  tests/integration_tests/functional/test_rate_limiter.py
Labels: Status: Awaiting review

#3969 test: Increases duration of delay for log message checker
  tests/framework/microvm.py
Labels: Status: Awaiting review, Type: Fix

#3974 fix(vmm): Changes T2A to set EferLmsleUnsupported to 1
  CHANGELOG.md
  resources/tests/static_cpu_templates/t2a.json
  src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2a.rs
Labels: Status: Awaiting review, Type: Fix

#3972 refactor: Simplify `build_microvm_from_requests`
  src/api_server/src/lib.rs
  src/firecracker/src/api_server_adapter.rs
  src/vmm/src/rpc_interface.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Awaiting review

#3977 chore: release v1.4.0
  CHANGELOG.md
  CREDITS.md
  Cargo.lock
  src/api_server/swagger/firecracker.yaml
  src/cpu-template-helper/Cargo.toml
  src/firecracker/Cargo.toml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  tests/host_tools/uffd/Cargo.lock
  tests/integration_tests/build/test_binary_size.py
  tests/integration_tests/security/demo_seccomp/Cargo.lock
Labels: Status: Awaiting review

#3978 fix: minor fix of `release.sh`
  tools/release.sh
Labels: Status: Awaiting review

#3874 fix(aarch64): removed warnings for missing cache info
  src/vmm/src/arch/aarch64/cache_info.rs
Labels: Status: Awaiting review, Type: Fix

#3979 fix(vmm): Changes T2A not to unset MMX and FXSR bits
  CHANGELOG.md
  resources/tests/static_cpu_templates/t2a.json
  src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2a.rs
  tests/integration_tests/functional/test_feat_parity.py
Labels: Status: Awaiting review, Type: Fix

#3981 chore: added 1.4 release to the RELEASE_POLICY doc
  docs/RELEASE_POLICY.md
Labels: Status: Awaiting review

#3982 fix(vmm): Changes T2A to set RstrFpErrPtrs bit
  CHANGELOG.md
  resources/tests/static_cpu_templates/t2a.json
  src/vmm/src/cpu_config/x86_64/static_cpu_templates/t2a.rs
  tests/integration_tests/functional/test_feat_parity.py
Labels: Status: Awaiting review, Type: Fix

#3988 chore: updated baselines for network latency for aarch64
  tests/integration_tests/performance/configs/test_network_latency_config_6.1.json
Labels: Status: Awaiting review, Type: Fix

#3989 chore: Update Slack invitation link
  README.md
Labels: Status: Awaiting review, Type: Documentation, Type: Fix

#3985 fix: update to cpu id validation during snapshot restoration
  CHANGELOG.md
  src/vmm/src/persist.rs
  src/vmm/tests/integration_tests.rs
Labels: Status: Awaiting review, Type: Fix

#3987 Adds stub for read_be_u16 to Kani harnesses
  src/dumbo/src/pdu/ethernet.rs
Labels: Status: Awaiting review

#3704 fix: Move `rate_limiter` into module under `vmm`
  Cargo.lock
  src/rate_limiter/Cargo.toml
  src/vmm/Cargo.toml
  src/vmm/src/devices/virtio/block/device.rs
  src/vmm/src/devices/virtio/block/persist.rs
  src/vmm/src/devices/virtio/block/request.rs
  src/vmm/src/devices/virtio/block/test_utils.rs
  src/vmm/src/devices/virtio/net/device.rs
  src/vmm/src/devices/virtio/net/persist.rs
  src/vmm/src/devices/virtio/net/test_utils.rs
  src/vmm/src/devices/virtio/rng/device.rs
  src/vmm/src/devices/virtio/rng/persist.rs
  src/vmm/src/lib.rs
  src/vmm/src/rate_limiter/mod.rs
  src/vmm/src/rate_limiter/persist.rs
  src/vmm/src/rpc_interface.rs
  src/vmm/src/vmm_config/drive.rs
  src/vmm/src/vmm_config/entropy.rs
  src/vmm/src/vmm_config/mod.rs
  src/vmm/src/vmm_config/net.rs
  tests/integration_tests/test_kani.py
Labels: Priority: Low, Status: Awaiting review, Type: Fix

#3991 test: Run unittests in debug mode
  tests/integration_tests/build/test_unittests.py
Labels: Status: Awaiting review

#3993 fix: specify resolver in Cargo.toml
  Cargo.toml
  src/firecracker/Cargo.toml
Labels: Status: Awaiting review
