Repository firecracker-microvm/firecracker, pull requests merged in 2023-10, with the labels that each got.

#4144 fix: add 640th KiB to the available memory
  src/vmm/src/arch/x86_64/mod.rs
Labels: Status: Awaiting review, Type: Fix

#4154 fix: restore the id parameter default
  src/firecracker/src/main.rs
  tests/integration_tests/functional/test_cmd_line_parameters.py
Labels: Priority: High, Type: Fix, Status: Awaiting author

#4174 docs: Add "deprecated" section to changelog
  CHANGELOG.md
Labels: Status: Awaiting review

#4177 docs: Update vmlinux patch version in getting-started.md
  docs/getting-started.md
Labels: Status: Awaiting review

#4178 fix: Pass through no-API shutdown exit code (main)
  CHANGELOG.md
  src/firecracker/src/main.rs
  tests/framework/vm_config_network.json
  tests/integration_tests/functional/test_cmd_line_start.py
Labels: Priority: High, Status: Awaiting review

#4179 fix: Pass through no-API shutdown exit code (1.5)
  CHANGELOG.md
  src/firecracker/src/main.rs
  tests/framework/vm_config_network.json
  tests/integration_tests/functional/test_cmd_line_start.py
Labels: Priority: High

#4189 fix block_ab and snapshot_ab after 4160
  tests/integration_tests/performance/test_block_ab.py
  tests/integration_tests/performance/test_snapshot_ab.py
Labels: Status: Awaiting review

#4180 fix: Refactor error propagation
  CHANGELOG.md
  src/firecracker/src/api_server_adapter.rs
  src/firecracker/src/main.rs
  tests/integration_tests/functional/test_cmd_line_start.py
Labels: Status: Awaiting review

#4197 chore(metrics): Test for breaking change in Firecracker metrics
  tests/integration_tests/functional/test_metrics.py
Labels: Status: Awaiting review

#4200 Update Getting started docs
  docs/getting-started.md
Labels: Status: Awaiting review

#4209 Marked `rebase-snap` as deprecated
  CHANGELOG.md
  docs/snapshotting/snapshot-editor.md
  docs/snapshotting/snapshot-support.md
  src/rebase-snap/src/main.rs
Labels: Status: Awaiting review, Type: Documentation
