Repository firecracker-microvm/firecracker, pull requests merged in 2023-04, with the labels that each got.

#3591 Possible race condition between VMM thread and API thread (FC 1.2)
  src/firecracker/src/api_server_adapter.rs
Labels: Status: Awaiting review

#3590 Possible race condition between VMM thread and API thread (FC 1.3)
  src/firecracker/src/api_server_adapter.rs
Labels: Status: Awaiting review

#3599 criterion: trim down dependencies
  Cargo.lock
  src/snapshot/Cargo.toml
  src/vmm/Cargo.toml
Labels: Status: Awaiting review

#3593 fix(vmm): undo removal of 0xb leaf on AMD for main branch
  CHANGELOG.md
  src/vmm/src/cpuid/transformer/amd.rs
  src/vmm/src/cpuid/transformer/common.rs
  src/vmm/src/cpuid/transformer/intel.rs
Labels: Status: Awaiting review, Type: Fix

#3598 feat: Static CPU templates in JSON format and `CpuTemplate` type
  Cargo.lock
  Cargo.toml
  src/static_templates/Cargo.toml
  src/static_templates/src/c3.rs
  src/static_templates/src/lib.rs
  src/static_templates/src/t2.rs
  src/static_templates/src/t2a.rs
  src/static_templates/src/t2cl.rs
  src/static_templates/src/t2s.rs
  src/static_templates/tests/integration_tests.rs
  src/static_templates/tests/json/c3.json
  src/static_templates/tests/json/t2.json
  src/static_templates/tests/json/t2a.json
  src/static_templates/tests/json/t2cl.json
  src/static_templates/tests/json/t2s.json
  src/static_templates/tests/main_branch/amd/mod.rs
  src/static_templates/tests/main_branch/amd/t2a.rs
  src/static_templates/tests/main_branch/bit_helper.rs
  src/static_templates/tests/main_branch/cpu_leaf.rs
  src/static_templates/tests/main_branch/intel/c3.rs
  src/static_templates/tests/main_branch/intel/mod.rs
  src/static_templates/tests/main_branch/intel/t2.rs
  src/static_templates/tests/main_branch/intel/t2cl.rs
  src/static_templates/tests/main_branch/intel/t2s.rs
  src/static_templates/tests/main_branch/mod.rs
  tests/framework/dependencies.txt
  tests/integration_tests/build/test_coverage.py
Labels: Status: Awaiting review, Type: Enhancement

#3589 `virtio-rng` documentation
  README.md
  docs/device-api.md
  docs/entropy.md
  docs/snapshotting/random-for-clones.md
Labels: Status: Awaiting review, Type: Enhancement

#3616 test: c7g & m6g network throughput baselines
  tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
  tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
Labels: Priority: High, Status: Awaiting review, Type: Fix

#3617 test: m6a vsock throughput baselines
  tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
  tests/integration_tests/performance/configs/test_vsock_throughput_config_5.10.json
Labels: Priority: High, Status: Awaiting review, Type: Fix

#3624 docs: update recommendation on ENOMEM
  FAQ.md
Labels: Status: Awaiting review, Type: Documentation

#3632 Backport Fix spurious failure in api_server::tests::test_serve_vmm_action_request to FC 1.3
  src/api_server/src/lib.rs
Labels: Status: Awaiting review

#3635 Backport Fix spurious failure in api_server::tests::test_serve_vmm_action_request to FC 1.2
  src/api_server/src/lib.rs
Labels: Status: Awaiting review

#3634 Remove CPU model validation from python tests
  tests/framework/utils_cpuid.py
  tests/integration_tests/build/test_coverage.py
Labels: Status: Awaiting review

#3614 feat: Add "cpu-config" field to config file
  src/vmm/src/device_manager/persist.rs
  src/vmm/src/resources.rs
  tests/framework/vm_config.json
  tests/integration_tests/functional/test_api.py
Labels: Status: Awaiting review, Type: Enhancement

#3642 chore: update release policy for patch releases FC 1.2.1 and 1.3.2
  CHANGELOG.md
  docs/RELEASE_POLICY.md
Labels: Priority: Medium, Status: Awaiting author

#3643 chore: release v1.3.2
  CHANGELOG.md
  Cargo.lock
  src/api_server/swagger/firecracker.yaml
  src/firecracker/Cargo.toml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  tests/integration_tests/security/demo_seccomp/Cargo.lock
Labels: Priority: High, Status: Awaiting review

#3641 Releasing v1.2.1
  CHANGELOG.md
  Cargo.lock
  src/api_server/swagger/firecracker.yaml
  src/firecracker/Cargo.toml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  tests/integration_tests/security/demo_seccomp/Cargo.lock
  tools/release-prepare.sh
Labels: Priority: High, Status: Awaiting review

#3605 Move --ignore RUSTSEC-2021-0145 to audit.toml
  .cargo/audit.toml
  tests/integration_tests/security/test_sec_audit.py
Labels: Status: Awaiting review

#3645 Add CHANGELOG entry for `virtio-rng`
  CHANGELOG.md
Labels: Status: Awaiting review, Type: Documentation
