Repository firecracker-microvm/firecracker, pull requests merged in 2023-05, with the labels that each got.

#3652 refactor(vmm): move cpuid under x86_64
  src/cpu-template-helper/src/dump/x86_64.rs
  src/cpu-template-helper/src/strip/x86_64.rs
  src/cpu-template-helper/src/utils/x86_64.rs
  src/cpu-template-helper/src/verify/x86_64.rs
  src/vmm/src/arch/x86_64/msr.rs
  src/vmm/src/builder.rs
  src/vmm/src/guest_config/mod.rs
  src/vmm/src/guest_config/templates/mod.rs
  src/vmm/src/guest_config/templates/test_utils/x86_64.rs
  src/vmm/src/guest_config/templates/x86_64.rs
  src/vmm/src/guest_config/x86_64/cpuid/amd/mod.rs
  src/vmm/src/guest_config/x86_64/cpuid/amd/normalize.rs
  src/vmm/src/guest_config/x86_64/cpuid/common.rs
  src/vmm/src/guest_config/x86_64/cpuid/intel/mod.rs
  src/vmm/src/guest_config/x86_64/cpuid/intel/normalize.rs
  src/vmm/src/guest_config/x86_64/cpuid/mod.rs
  src/vmm/src/guest_config/x86_64/cpuid/normalize.rs
  src/vmm/src/guest_config/x86_64/mod.rs
  src/vmm/src/guest_config/x86_64/static_cpu_templates/c3.rs
  src/vmm/src/guest_config/x86_64/static_cpu_templates/t2.rs
  src/vmm/src/guest_config/x86_64/static_cpu_templates/t2a.rs
  src/vmm/src/guest_config/x86_64/static_cpu_templates/t2cl.rs
  src/vmm/src/guest_config/x86_64/static_cpu_templates/t2s.rs
  src/vmm/src/persist.rs
  src/vmm/src/vstate/vcpu/mod.rs
  src/vmm/src/vstate/vcpu/x86_64.rs
Labels: Status: Awaiting review

#3663 added /cpu-config api tests
  tests/integration_tests/functional/test_api.py
Labels: Status: Awaiting review, Type: Enhancement

#3585 Add dependabot configuration
  .github/dependabot.yml
Labels: Priority: High, Status: Awaiting review

#3674 dependabot: fix label name
  .github/dependabot.yml
Labels: Status: Awaiting review

#3679 remove "push" target from GitHub actions
  .github/workflows/deny_dirty_cargo_locks.yml
  .github/workflows/dependency_modification_check.yml
Labels: Status: Awaiting review

#3681 chore(gitlint): reenable check for presence of message body
  .gitlint
Labels: Status: Awaiting review

#3688 chore(tests): run test_cpu_config_change only for supported kernels
  tests/integration_tests/functional/test_cpu_template_helper.py
Labels: Status: Awaiting review

#3689 fix: fixed bug in deserialization method
  src/vmm/src/cpu_config/aarch64/custom_cpu_template.rs
  src/vmm/src/cpu_config/templates_serde.rs
  src/vmm/src/cpu_config/x86_64/custom_cpu_template.rs
Labels: Status: Awaiting review, Type: Fix

#3696 Bump version to 1.5.0-dev
  Cargo.lock
  src/api_server/swagger/firecracker.yaml
  src/cpu-template-helper/Cargo.toml
  src/firecracker/Cargo.toml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  src/vmm/src/version_map.rs
  tests/host_tools/uffd/Cargo.lock
  tests/integration_tests/security/demo_seccomp/Cargo.lock
Labels: Priority: High, Status: Awaiting review

#3697 Warn about arm register width problem
  README.md
  docs/snapshotting/snapshot-support.md
Labels: Status: Awaiting review, Type: Documentation

#3702 chore: update m5d snap restore baselines
  tests/integration_tests/performance/configs/test_snapshot_restore_performance_config_4.14.json
Labels: Status: Awaiting review

#3703 fix: Move `io_uring` into module under `vmm`
  Cargo.lock
  src/io_uring/Cargo.toml
  src/io_uring/tests/test_utils/mod.rs
  src/vmm/Cargo.toml
  src/vmm/src/devices/virtio/block/io/async_io.rs
  src/vmm/src/io_uring/bindings.rs
  src/vmm/src/io_uring/mod.rs
  src/vmm/src/io_uring/operation/cqe.rs
  src/vmm/src/io_uring/operation/mod.rs
  src/vmm/src/io_uring/operation/sqe.rs
  src/vmm/src/io_uring/probe.rs
  src/vmm/src/io_uring/queue/completion.rs
  src/vmm/src/io_uring/queue/mmap.rs
  src/vmm/src/io_uring/queue/mod.rs
  src/vmm/src/io_uring/queue/submission.rs
  src/vmm/src/io_uring/restriction.rs
  src/vmm/src/lib.rs
  src/vmm/tests/io_uring.rs
  tests/integration_tests/style/test_rust.py
Labels: Priority: Low, Status: Awaiting review, Type: Fix

#3709 Mention virtio-rng in CHANGELOG
  CHANGELOG.md
Labels: Status: Awaiting review, Type: Documentation

#3714 handle 0 size buffers from guest
  src/vmm/src/devices/virtio/rng/device.rs
Labels: Status: Awaiting review

#3715 Backport 0 size buffers fix
  src/devices/src/virtio/rng/device.rs
Labels: Status: Awaiting review

#3660 README.md: dark/light mode logo
  README.md
Labels: Status: Awaiting review

#3727 Release Firecracker v1.3.3
  CHANGELOG.md
  Cargo.lock
  src/api_server/swagger/firecracker.yaml
  src/firecracker/Cargo.toml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  tests/integration_tests/security/demo_seccomp/Cargo.lock
Labels: Status: Awaiting review

#3728 [1.2] chore(changelog): fix version of the upgraded rust in 1.2.1
  CHANGELOG.md
Labels: Status: Awaiting review

#3729 ci: teach devtool to run shell commands inside devctr
  tools/devtool
Labels: Priority: High, Status: Awaiting review, Release

#3732 [v1.2] ci: teach devtool to run shell commands inside devctr
  tools/devtool
Labels: Priority: High, Status: Awaiting review, Release

#3731 [v1.3] ci: teach devtool to run shell commands inside devctr
  tools/devtool
Labels: Priority: High, Status: Awaiting review, Release

#3738 Backport PR #3523 to firecracker-v1.3
  tests/framework/utils.py
Labels: Type: Fix

#3737 Backport PR #3523 to firecracker-v1.2
  tests/framework/utils.py
Labels: Type: Fix

#3749 Update dependencies by cherry-picking dependabot PRs
  Cargo.lock
Labels: Status: Awaiting review, dependencies

#3752 refactor(test): Delete duplicate function definition
  tests/framework/properties.py
  tests/integration_tests/functional/test_rng.py
Labels: Status: Awaiting review

#3756 Backport "fix(tests): test_balloon_snapshot: add delay after inflate" to v1.2
  tests/integration_tests/functional/test_balloon.py
Labels: Status: Awaiting review, Type: Fix

#3705 fix: appease clippy in vmm integration tests
  src/vmm/tests/devices.rs
  src/vmm/tests/integration_tests.rs
  src/vmm/tests/io_uring.rs
Labels: Status: Awaiting review

#3754 refactor(vmm): Remove aarch64 core register exception
  src/vmm/src/vstate/vcpu/aarch64.rs
Labels: Status: Awaiting review, Type: Fix

#3755 devtool/checkev: update checks according to the prod host setup guide
  tools/devtool
Labels: Status: Awaiting review

#3766 chore(test): Update performance baseline
  tests/integration_tests/performance/configs/test_network_tcp_throughput_config_5.10.json
Labels: Status: Awaiting review
