Repository firecracker-microvm/firecracker, pull requests merged in 2023-11, with the labels that each got.

#4196 test(ab): artificially increase network latency test cases
  tests/integration_tests/performance/test_network_ab.py
Labels: Status: Awaiting review

#4216 feat: add a debug log for vm build time
  src/vmm/src/builder.rs
  tests/integration_tests/performance/test_boottime.py
Labels: Priority: Low, Status: Awaiting author

#4222 fix(rebase-snap): Move deprecation message after version info
  src/rebase-snap/src/main.rs
Labels: Status: Awaiting review, Type: Fix

#4214 chore(logs): removed redundant `debug!` logs
  src/vmm/src/devices/virtio/balloon/event_handler.rs
  src/vmm/src/devices/virtio/net/event_handler.rs
  src/vmm/src/devices/virtio/rng/device.rs
  src/vmm/src/devices/virtio/virtio_block/event_handler.rs
  src/vmm/src/devices/virtio/vsock/device.rs
  src/vmm/src/devices/virtio/vsock/event_handler.rs
  src/vmm/src/devices/virtio/vsock/unix/muxer.rs
Labels: Status: Awaiting review, Type: Fix

#4218 build: `-Ccodegen-units=1`
  .cargo/config
Labels: Status: Awaiting review

#4237 test(perf): omit randwrite test for vhost-user-blk
  tests/integration_tests/performance/test_block_ab.py
  tests/integration_tests/performance/test_block_performance.py
Labels: Status: Awaiting review

#4244 fix: Downgrade #![deny(...)] to #![warn(...)]
  src/api_server/src/lib.rs
  src/seccompiler/src/lib.rs
  src/snapshot/src/lib.rs
  src/utils/src/net/mod.rs
  src/vmm/src/dumbo/mod.rs
  src/vmm/src/io_uring/mod.rs
  src/vmm/src/lib.rs
  src/vmm/src/logger/mod.rs
  src/vmm/src/rate_limiter/mod.rs
Labels: Status: Awaiting review

#4210 doc: add vhost-user-blk documentation
  CHANGELOG.md
  docs/api_requests/block-io-engine.md
  docs/api_requests/block-vhost-user.md
  docs/api_requests/patch-block.md
  docs/design.md
  docs/device-api.md
  src/api_server/swagger/firecracker.yaml
Labels: Status: Awaiting review

#4248 doc: Add kernel pre-requisites for vsock
  docs/vsock.md
Labels: Status: Awaiting review

#4251 chore(vhost-user-block): updated log message for init event
  src/vmm/src/devices/virtio/vhost_user_block/event_handler.rs
Labels: Status: Awaiting review

#4254 test: Fix default handling of pipeline_perf --test argument
  .buildkite/pipeline_perf.py
Labels: Status: Awaiting review

#4255 Revert "ci: skip boottime SLA in m6i Linux 6.1"
  tests/integration_tests/performance/test_boottime.py
Labels: Status: Awaiting review

#4260 doc(changelog): deduplicate vhost-user-blk entries
  CHANGELOG.md
Labels: Status: Awaiting review

#4267 fix: Trigger A/B-Test runs by $GITHUB_REF_NAME
  .github/workflows/trigger_ab_tests.yml
Labels: Status: Awaiting review

#4268 fix: environment variables dont interpolate with single quotes
  .github/workflows/trigger_ab_tests.yml
Labels: Status: Awaiting review

#4259 Use the double fork method to daemonize jailer
  docs/jailer.md
  src/jailer/src/env.rs
  src/jailer/src/main.rs
Labels: Status: Awaiting review

#4242 fix: Support all logger level case variants
  Cargo.lock
  src/vmm/Cargo.toml
  src/vmm/src/logger/logging.rs
Labels: Status: Awaiting review

#4262 Make ab_test.py print relative delta of changes
  tools/ab_test.py
Labels: Status: Awaiting review

#4269 fix(drive): made FileEngineType optional
  src/vmm/src/builder.rs
  src/vmm/src/devices/virtio/vhost_user_block/device.rs
  src/vmm/src/devices/virtio/virtio_block/device.rs
  src/vmm/src/resources.rs
  src/vmm/src/rpc_interface.rs
  src/vmm/src/vmm_config/drive.rs
  tests/integration_tests/functional/test_api.py
Labels: Status: Awaiting review, Type: Fix

#4272 Changelog for 4261 and 4242
  CHANGELOG.md
Labels: Status: Awaiting review

#4278 fix: intermittent vsock timeout in snapshot tests
  tests/integration_tests/functional/test_snapshot_basic.py
Labels: Status: Awaiting review

#4246 test(metrics): collect Firecracker vhost-user metrics
  tests/integration_tests/performance/test_vhost_user_metrics.py
Labels: Status: Awaiting review

#4264 test(vhost-user-blk): move backend management to microvm class
  tests/framework/microvm.py
  tests/framework/utils_drive.py
  tests/integration_tests/functional/test_api.py
  tests/integration_tests/functional/test_drive_vhost_user.py
  tests/integration_tests/performance/test_block_ab.py
  tests/integration_tests/performance/test_vhost_user_metrics.py
Labels: Status: Awaiting review
