Repository firecracker-microvm/firecracker, pull requests merged in 2023-12, with the labels that each got.

#4292 fix(test): do not pass network config to CPU template helper
  tests/integration_tests/functional/test_cpu_template_helper.py
Labels: Status: Awaiting review

#4294 doc: add fix for async engine in CHANGELOG
  CHANGELOG.md
Labels: Status: Awaiting review

#4290 build: Move `env_logger` to `dev-dependencies` of `log-instrument`
  src/log-instrument/Cargo.toml
Labels: Status: Awaiting review

#4299 chore: update base64 dependency from 0.13.0 to 0.21.0
  Cargo.lock
  src/vmm/Cargo.toml
  src/vmm/src/mmds/token.rs
Labels: Status: Awaiting review

#4027 fix: Inline `log_received_api_request`
  src/api_server/src/parsed_request.rs
Labels: Priority: Low, Status: Awaiting review, Type: Fix

#4307 test(repo): ensure CHANGELOG.md is valid
  CHANGELOG.md
  tests/integration_tests/style/test_repo.py
Labels: Type: Documentation, Release

#4314 ci: Disable A/B tests failing on m6i.metal 5.10
  tools/ab_test.py
Labels: Status: Awaiting review

#4330 chore: bump version to 1.7.0-dev
  Cargo.lock
  docs/getting-started.md
  src/api_server/swagger/firecracker.yaml
  src/cpu-template-helper/Cargo.toml
  src/firecracker/Cargo.toml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  src/snapshot-editor/Cargo.toml
  src/vmm/src/version_map.rs
  tools/devtool
Labels: Priority: Medium, Status: Awaiting review

#4331 doc: fix getting-started guide
  docs/getting-started.md
Labels: Priority: Medium, Status: Awaiting review, Type: Documentation

#4328 Update seccomp filters for rust toolchain upgrade
  resources/seccomp/aarch64-unknown-linux-musl.json
  resources/seccomp/x86_64-unknown-linux-musl.json
Labels: Status: Awaiting review

#4326 chore: Add rust-toolchain.toml file to repository
  rust-toolchain.toml
Labels: Status: Awaiting review

#4339 fix: Use the right url to view the release
  .github/workflows/send_release_notification.yml
Labels: Status: Awaiting review
