Repository firecracker-microvm/firecracker, pull requests merged in 2023-03, with the labels that each got.

#3485 chore: new c7g.metal performance baselines
  tests/integration_tests/performance/configs/test_network_latency_config_4.14.json
  tests/integration_tests/performance/configs/test_network_tcp_throughput_config_4.14.json
  tests/integration_tests/performance/configs/test_vsock_throughput_config_4.14.json
Labels: Performance: Misc, Status: Reviewer

#3490 Releasing v1.3.0
  .mailmap
  CHANGELOG.md
  CREDITS.md
  Cargo.lock
  src/api_server/swagger/firecracker.yaml
  src/firecracker/Cargo.toml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  tests/integration_tests/security/demo_seccomp/Cargo.lock
Labels: Quality: Release

#3495 Refuse to release if the snapshot version is missing
  tools/release-prepare.sh
Labels: Quality: CI, Status: Reviewer, Quality: Release

#3500 Include `spectre-meltdown-checker.sh` in `prod-host-setup.md`
  docs/prod-host-setup.md
Labels: Documentation: Usage

#3484 docs: Update `getting-started.md`
  docs/getting-started.md
Labels: Documentation: Usage

#3438 fix: Move `cpuid` into module under `vmm`
  Cargo.lock
  src/cpuid/Cargo.toml
  src/vmm/Cargo.toml
  src/vmm/src/builder.rs
  src/vmm/src/cpuid/bit_helper.rs
  src/vmm/src/cpuid/brand_string.rs
  src/vmm/src/cpuid/common.rs
  src/vmm/src/cpuid/cpu_leaf.rs
  src/vmm/src/cpuid/mod.rs
  src/vmm/src/cpuid/template/amd/mod.rs
  src/vmm/src/cpuid/template/amd/t2a.rs
  src/vmm/src/cpuid/template/intel/c3.rs
  src/vmm/src/cpuid/template/intel/mod.rs
  src/vmm/src/cpuid/template/intel/t2.rs
  src/vmm/src/cpuid/template/intel/t2cl.rs
  src/vmm/src/cpuid/template/intel/t2s.rs
  src/vmm/src/cpuid/template/mod.rs
  src/vmm/src/cpuid/transformer/amd.rs
  src/vmm/src/cpuid/transformer/common.rs
  src/vmm/src/cpuid/transformer/intel.rs
  src/vmm/src/cpuid/transformer/mod.rs
  src/vmm/src/lib.rs
  src/vmm/src/persist.rs
  src/vmm/src/vstate/vcpu/x86_64.rs
  src/vmm/tests/integration_tests.rs
Labels: Codebase: Architecture

#3509 fix: Move `arch` into module under `vmm`
  Cargo.lock
  src/arch/Cargo.toml
  src/vmm/Cargo.toml
  src/vmm/src/arch/aarch64/cache_info.rs
  src/vmm/src/arch/aarch64/fdt.rs
  src/vmm/src/arch/aarch64/gic/gicv2/mod.rs
  src/vmm/src/arch/aarch64/gic/gicv2/regs/dist_regs.rs
  src/vmm/src/arch/aarch64/gic/gicv2/regs/icc_regs.rs
  src/vmm/src/arch/aarch64/gic/gicv2/regs/mod.rs
  src/vmm/src/arch/aarch64/gic/gicv3/mod.rs
  src/vmm/src/arch/aarch64/gic/gicv3/regs/dist_regs.rs
  src/vmm/src/arch/aarch64/gic/gicv3/regs/icc_regs.rs
  src/vmm/src/arch/aarch64/gic/gicv3/regs/mod.rs
  src/vmm/src/arch/aarch64/gic/gicv3/regs/redist_regs.rs
  src/vmm/src/arch/aarch64/gic/mod.rs
  src/vmm/src/arch/aarch64/gic/regs.rs
  src/vmm/src/arch/aarch64/layout.rs
  src/vmm/src/arch/aarch64/mod.rs
  src/vmm/src/arch/aarch64/output_GICv2.dtb
  src/vmm/src/arch/aarch64/output_GICv3.dtb
  src/vmm/src/arch/aarch64/output_initrd_GICv2.dtb
  src/vmm/src/arch/aarch64/output_initrd_GICv3.dtb
  src/vmm/src/arch/aarch64/regs.rs
  src/vmm/src/arch/mod.rs
  src/vmm/src/arch/x86_64/cpu_model.rs
  src/vmm/src/arch/x86_64/gdt.rs
  src/vmm/src/arch/x86_64/interrupts.rs
  src/vmm/src/arch/x86_64/layout.rs
  src/vmm/src/arch/x86_64/mod.rs
  src/vmm/src/arch/x86_64/mptable.rs
  src/vmm/src/arch/x86_64/msr.rs
  src/vmm/src/arch/x86_64/regs.rs
  src/vmm/src/builder.rs
  src/vmm/src/cpuid/common.rs
  src/vmm/src/cpuid/template/intel/t2cl.rs
  src/vmm/src/cpuid/template/intel/t2s.rs
  src/vmm/src/device_manager/mmio.rs
  src/vmm/src/device_manager/persist.rs
  src/vmm/src/lib.rs
  src/vmm/src/persist.rs
  src/vmm/src/vmm_config/boot_source.rs
  src/vmm/src/vstate/vcpu/aarch64.rs
  src/vmm/src/vstate/vcpu/mod.rs
  src/vmm/src/vstate/vcpu/x86_64.rs
  src/vmm/src/vstate/vm.rs
  src/vmm/tests/integration_tests.rs
  tests/framework/dependencies.txt
Labels: Codebase: Architecture

#3529 fix: fix Slack notification on pr
  .github/workflows/send_pr_notification.yml
Labels: Status: Reviewer

#3533 tools: bump devctr version to v53
  .buildkite/common.py
  tests/integration_tests/style/test_python.py
  tools/devctr/poetry.lock
  tools/devtool
Labels: Quality: CI, Status: Reviewer

#3527 doc: Add doc strings for public items in vcpu module
  src/vmm/src/lib.rs
  src/vmm/src/vstate/vcpu/mod.rs
  src/vmm/src/vstate/vm.rs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Reviewer

#3523 Add error handling when screen/firecracker processes have not launched successfully
  tests/framework/utils.py
Labels: Codebase: Usability

#3332 Add guest concurrency test with MMDS usage
  tests/framework/utils.py
  tests/integration_tests/functional/test_concurrency.py
  tests/integration_tests/functional/test_mmds.py
  tests/integration_tests/functional/test_snapshot_restore_cross_kernel.py
Labels: Codebase: Refactoring, Codebase: Build System

#3538 tools: move package installation to Dockerfile
  resources/tests/build_kernel.sh
  tools/devctr/Dockerfile
  tools/devtool
Labels: Quality: CI, Quality: Automated Testing, Status: Reviewer

#3544 fix: Remove bit-fields
  Cargo.lock
  src/bit-fields-macros/Cargo.toml
  src/bit-fields-macros/src/builder.rs
  src/bit-fields-macros/src/lib.rs
  src/bit-fields-macros/src/parser.rs
  src/bit-fields-macros/src/utils.rs
  src/bit-fields/Cargo.toml
  src/bit-fields/src/bit.rs
  src/bit-fields/src/bit_range.rs
  src/bit-fields/src/errors.rs
  src/bit-fields/src/example.rs
  src/bit-fields/src/lib.rs
  src/vmm/Cargo.toml
  src/vmm/src/guest_config/cpuid/amd/indexing.rs
  src/vmm/src/guest_config/cpuid/amd/leaves.rs
  src/vmm/src/guest_config/cpuid/amd/mod.rs
  src/vmm/src/guest_config/cpuid/amd/normalize.rs
  src/vmm/src/guest_config/cpuid/amd/registers.rs
  src/vmm/src/guest_config/cpuid/cpuid_ffi.rs
  src/vmm/src/guest_config/cpuid/indexing.rs
  src/vmm/src/guest_config/cpuid/intel/indexing.rs
  src/vmm/src/guest_config/cpuid/intel/leaves.rs
  src/vmm/src/guest_config/cpuid/intel/mod.rs
  src/vmm/src/guest_config/cpuid/intel/normalize.rs
  src/vmm/src/guest_config/cpuid/intel/registers.rs
  src/vmm/src/guest_config/cpuid/leaves.rs
  src/vmm/src/guest_config/cpuid/mod.rs
  src/vmm/src/guest_config/cpuid/normalize.rs
  src/vmm/src/guest_config/cpuid/registers.rs
  tests/framework/dependencies.txt
  tests/integration_tests/build/test_coverage.py
Labels: Codebase: Architecture, Feature: CPU Configuration, Status: Reviewer

#3563 gitlint: Ignore dependabot commits
  .gitlint
Labels: Status: Awaiting review

#3565 Fix .gitlint comment
  .gitlint
Labels: Status: Awaiting review

#3569 test: Cleanup file created by cmd_test
  tools/devtool
Labels: Status: Awaiting review

#3537 fix: use `thiserror::Error` in vmm
  src/vmm/src/device_manager/legacy.rs
  src/vmm/src/vstate/system.rs
  src/vmm/src/vstate/vcpu/x86_64.rs
  tests/integration_tests/build/test_coverage.py
Labels: Priority: Low, Status: Awaiting review, Type: Fix

#3530 test: Update `test_ensure_mod_tests`
  tests/integration_tests/style/test_rust.py
Labels: Priority: Medium, Status: Awaiting review, Type: Enhancement

#3528 fix: Move `arch_gen` into module under `vmm`
  Cargo.lock
  src/arch_gen/Cargo.toml
  src/vmm/Cargo.toml
  src/vmm/src/arch/x86_64/mptable.rs
  src/vmm/src/arch/x86_64/msr.rs
  src/vmm/src/arch_gen/mod.rs
  src/vmm/src/arch_gen/x86/mod.rs
  src/vmm/src/arch_gen/x86/mpspec.rs
  src/vmm/src/arch_gen/x86/msr_index.rs
  src/vmm/src/cpuid/template/mod.rs
  src/vmm/src/lib.rs
  tools/bindgen.sh
Labels: Priority: Low, Status: Awaiting review, Type: Fix
