Repository firecracker-microvm/firecracker, pull requests merged in 2023-08, with the labels that each got.

#3951 feat: use `semver` crate for firecracker versions
  Cargo.lock
  src/api_server/src/request/snapshot.rs
  src/firecracker/src/main.rs
  src/vmm/Cargo.toml
  src/vmm/src/persist.rs
  src/vmm/src/version_map.rs
  src/vmm/src/vmm_config/snapshot.rs
  src/vmm/tests/integration_tests.rs
  tests/integration_tests/functional/test_snapshot_version.py
Labels: Type: Enhancement

#4001 chore: update baseline for vsock throughput for m6g.metal+6.1 kv
  tests/integration_tests/performance/configs/test_vsock_throughput_config_6.1.json
Labels: Status: Awaiting review

#4002 Fix: Ignore frequency from host brand string in normalize
  src/vmm/src/cpu_config/x86_64/cpuid/intel/normalize.rs
Labels: Status: Awaiting review

#4005 chore: update vsock perf baseline for m6a and c7g for 6.1
  tests/integration_tests/performance/configs/test_vsock_throughput_config_6.1.json
Labels: Status: Awaiting review

#4007 Fix: Ignore frequency from host brand string in normalize
  src/vmm/src/cpu_config/x86_64/cpuid/intel/normalize.rs
Labels: Status: Awaiting review

#3996 Update all error structs/enums to use thiserror::Error
  src/vmm/src/arch/x86_64/regs.rs
  src/vmm/src/builder.rs
  src/vmm/src/lib.rs
  src/vmm/src/vmm_config/balloon.rs
  src/vmm/src/vmm_config/vsock.rs
  src/vmm/src/vstate/vcpu/mod.rs
Labels: Type: Enhancement

#4009 chore: release v1.4.1
  CHANGELOG.md
  Cargo.lock
  src/api_server/swagger/firecracker.yaml
  src/cpu-template-helper/Cargo.toml
  src/firecracker/Cargo.toml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  tests/host_tools/uffd/Cargo.lock
  tests/integration_tests/security/demo_seccomp/Cargo.lock
Labels: Status: Awaiting review

#4020 Small fixes
  src/logger/src/lib.rs
Labels: Status: Awaiting review

#4022 fix: handle BUILDKITE_PULL_REQUEST correctly for non PRs
  tests/integration_tests/build/test_coverage.py
Labels: Status: Awaiting review

#4017 feat: Simplify error logging
  src/firecracker/src/main.rs
  src/logger/src/logger.rs
Labels: Status: Awaiting review

#4031 refactor: Replace redundant `serde_json::from_slice(x.as_bytes())`
  src/cpu-template-helper/src/main.rs
  src/vmm/src/resources.rs
Labels: Priority: Low, Status: Awaiting review, Type: Fix

#4032 doc: update quickstart artifacts
  docs/getting-started.md
Labels: Status: Awaiting review, Type: Documentation

#4018 test: add a test to measure Firecracker memory overhead
  tests/integration_tests/build/test_binary_size.py
  tests/integration_tests/performance/test_memory_overhead.py
Labels: Priority: Medium, Status: Awaiting review, python

#4044 test: Update DEFAULT_G3_FEATURES_NO_SSBS to match new ci artifacts
  tests/integration_tests/functional/test_cpu_features_aarch64.py
Labels: Status: Awaiting review

#4029 test: Expand ignore list of CPUID leaves in test_cpu_config_dump_vs_actual
  tests/conftest.py
  tests/integration_tests/functional/test_cpu_template_helper.py
Labels: Status: Awaiting review, Type: Fix

#4074 ci: Skip 5.10 sky lake bootime test
  tests/integration_tests/performance/test_boottime.py
Labels: Priority: High, Status: Awaiting review

#4078 Mark snapshot-editor as not containing benchmarks
  src/snapshot-editor/Cargo.toml
Labels: Status: Awaiting review
