Repository firecracker-microvm/firecracker, pull requests merged in 2023-01, with the labels that each got.

#3356 fix(tests): mark monitoring threads as daemonic
  tests/framework/microvm.py
  tests/host_tools/memory.py
  tests/integration_tests/performance/test_network_latency.py
Labels: Quality: CI, Status: Author

#3367 fix: cargo audit timeout
  tools/devctr/Dockerfile.aarch64
  tools/devctr/Dockerfile.x86_64
  tools/devtool
Labels: Quality: CI

#3366 fix: `htons_unchecked` and `htonl_unchecked`
  src/dumbo/src/pdu/bytes.rs
Labels: Quality: Bug

#3336 Add link to nc-vsock tool in the documentation
  docs/vsock.md
Labels: Documentation: Usage, Status: Reviewer

#3076 CPUID (3/3): CPUID template expansion
  Cargo.lock
  Cargo.toml
  src/arch/src/x86_64/msr.rs
  src/bit-fields/src/bit_range.rs
  src/cpuid-templates/Cargo.toml
  src/cpuid-templates/src/lib.rs
  src/cpuid/Cargo.toml
  src/cpuid/build.rs
  src/cpuid/src/amd/indexing.rs
  src/cpuid/src/amd/leaves.rs
  src/cpuid/src/amd/mod.rs
  src/cpuid/src/amd/normalize.rs
  src/cpuid/src/amd/registers.rs
  src/cpuid/src/bit_helper.rs
  src/cpuid/src/brand_string.rs
  src/cpuid/src/common.rs
  src/cpuid/src/cpu_leaf.rs
  src/cpuid/src/cpuid_ffi.rs
  src/cpuid/src/indexing.rs
  src/cpuid/src/intel/indexing.rs
  src/cpuid/src/intel/leaves.rs
  src/cpuid/src/intel/mod.rs
  src/cpuid/src/intel/normalize.rs
  src/cpuid/src/intel/registers.rs
  src/cpuid/src/leaves.rs
  src/cpuid/src/lib.rs
  src/cpuid/src/normalize.rs
  src/cpuid/src/registers.rs
  src/cpuid/src/template/intel/c3.rs
  src/cpuid/src/template/intel/mod.rs
  src/cpuid/src/template/intel/t2.rs
  src/cpuid/src/template/intel/t2s.rs
  src/cpuid/src/template/mod.rs
  src/cpuid/src/transformer/amd.rs
  src/cpuid/src/transformer/common.rs
  src/cpuid/src/transformer/intel.rs
  src/cpuid/src/transformer/mod.rs
  src/logger/src/metrics.rs
  src/vmm/Cargo.toml
  src/vmm/src/builder.rs
  src/vmm/src/persist.rs
  src/vmm/src/vmm_config/machine_config.rs
  src/vmm/src/vstate/vcpu/x86_64.rs
  src/vmm/tests/integration_tests.rs
  tests/framework/dependencies.txt
  tests/integration_tests/build/test_coverage.py
  tests/integration_tests/functional/test_api.py
  tests/integration_tests/functional/test_cpu_features.py
Labels: Feature: CPU Configuration, Status: Reviewer

#3376 Fix the documentation in function of dumbo crate
  src/dumbo/src/lib.rs
  src/dumbo/src/pdu/tcp.rs
Labels: Status: Reviewer

#3326 test: add spectre/meltdown checker
  resources/guest_configs/microvm-kernel-ci-arm64-4.14.config
  resources/guest_configs/microvm-kernel-ci-arm64-5.10.config
  resources/guest_configs/microvm-kernel-ci-x86_64-4.14.config
  resources/guest_configs/microvm-kernel-ci-x86_64-5.10.config
  resources/tests/setup_rootfs.sh
  tests/conftest.py
  tests/integration_tests/security/test_spectre_meltdown.py
  tests/integration_tests/security/test_ssbd_mitigation.py
Labels: Quality: CI

#3388 test: remove resource dir when cleaning up microvm_factory
  tests/conftest.py
Labels: Status: Reviewer

#3394 fix(tests): test_balloon_snapshot: add delay after inflate
  tests/integration_tests/functional/test_balloon.py
Labels: Status: Reviewer

#3403 test: Update Arm start-up time
  tests/integration_tests/performance/test_process_startup_time.py
Labels: Performance: Boot Time
