Repository firecracker-microvm/firecracker, pull requests merged in 2024-04, with the labels that each got.

#4388 skipped unnecessary kvm_immediate_exits
  src/vmm/src/vstate/vcpu/mod.rs
Labels: Status: Awaiting review

#4477 [doc] Fix getting started permission problems
  docs/getting-started.md
Labels: Status: Awaiting review

#4541 Update schema to validate breaking change in metrics
  tests/host_tools/fcmetrics.py
Labels: Status: Awaiting review

#4551 chore: Update TODO in artifacts.py
  tests/framework/artifacts.py
Labels: Status: Awaiting review

#4552 Wait for VM to boot in A/B snapshot test
  tests/integration_tests/performance/test_snapshot_ab.py
Labels: Status: Awaiting review

#4553 test(cmdline): add delay for serial output file to appear
  tests/framework/microvm.py
Labels: Status: Awaiting review

#4554 test(balloon): add delay in stats update test
  tests/integration_tests/functional/test_balloon.py
Labels: Status: Awaiting review

#4570 chore: Pin 5.10 kernel AMIs
  .buildkite/common.py
Labels: Status: Awaiting review

#4572 chore: Update fingerprints
  tests/data/cpu_template_helper/fingerprint_AMD_MILAN_4.14host.json
  tests/data/cpu_template_helper/fingerprint_AMD_MILAN_5.10host.json
  tests/data/cpu_template_helper/fingerprint_AMD_MILAN_6.1host.json
  tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_N1_4.14host.json
  tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_N1_5.10host.json
  tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_N1_6.1host.json
  tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_V1_4.14host.json
  tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_V1_5.10host.json
  tests/data/cpu_template_helper/fingerprint_ARM_NEOVERSE_V1_6.1host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_4.14host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_5.10host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_6.1host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_ICELAKE_4.14host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_ICELAKE_5.10host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_ICELAKE_6.1host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_4.14host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_5.10host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_6.1host.json
Labels: Status: Awaiting review

#4567 fix: power off vcpus only during startup
  src/vmm/src/vstate/vcpu/aarch64.rs
Labels: Status: Awaiting review, Type: Fix

#4571 fix: update aarch64 cache topology tests for newer kernels
  tests/integration_tests/functional/test_topology.py
Labels: Status: Awaiting review, Type: Fix

#4583 test-popular-containers: add ubuntu 23.10 and 24.04
  tools/test-popular-containers/build_rootfs.sh
Labels: Priority: Medium, Status: Awaiting review
