Repository firecracker-microvm/firecracker, pull requests merged in 2024-12, with the labels that each got.

#4937 devtool: add download_ci_artifacts command
  tools/devtool
Labels: Status: Awaiting review

#4933 test: use pinned ami for m6i/6.1
  .buildkite/pipeline_perf.py
Labels: Status: Awaiting review

#4940 devtool: stop asking for user confirmation on container pull
  tools/devtool
  tools/functions
Labels: Status: Awaiting review

#4939 [CI] Add support for M7a detection in tests
  tests/framework/utils_cpuid.py
  tests/integration_tests/functional/test_cpu_features_x86_64.py
Labels: Status: Awaiting review

#4946 fix(tests): save snapshot metadata when saving to disk
  tests/framework/microvm.py
Labels: Priority: High, Status: Awaiting review, Type: Fix

#4949 fix(tests): add switch case for AMD_GENOA to the cpu features test
  tests/integration_tests/functional/test_cpu_features_host_vs_guest.py
Labels: Status: Awaiting review, Type: Fix

#4947 tests: flesh out the AMD Genoa host vs guest test
  tests/integration_tests/functional/test_cpu_features_host_vs_guest.py
Labels: Priority: Medium, Status: Awaiting review, python

#4957 tests: compile test_syscall with musl-gcc
  tests/host_tools/test_syscalls.c
  tests/integration_tests/security/test_seccomp_validate.py
Labels: Priority: Low, Status: Awaiting review

#4959 fix(test): ensure socat gets killed in test_5_snapshots
  tests/framework/utils_vsock.py
Labels: Status: Awaiting review

#4961 test: use fio instead of dd for performance tests
  tests/integration_tests/performance/test_drive_rate_limiter.py
Labels: Status: Awaiting review

#4960 tests: prevent double publishing of metrics
  tests/conftest.py
Labels: Type: Bug, Priority: Low, Status: Awaiting review, python

#4964 Ignore `tx_flush_fails` in tests
  tests/host_tools/fcmetrics.py
Labels: Priority: Low, Status: Awaiting review, python

#4971 chore: unpin m6i/6.1 ami
  .buildkite/pipeline_perf.py
Labels: Status: Awaiting review

#4968 test(wrmsr): exclude MSR_IA32_SPEC_CTRL from check
  tests/data/msr/wrmsr_list.txt
Labels: Status: Awaiting review

#4975 test: Add pytest option to apply custom CPU template to any microVM
  tests/conftest.py
  tests/framework/microvm.py
Labels: Status: Awaiting review, python
