Repository firecracker-microvm/firecracker, pull requests merged in 2024-09, with the labels that each got.

#4765 Increase timeout of kani tests
  tests/integration_tests/test_kani.py
Labels: Status: Awaiting review

#4766 Backport timeout fix for kani into firecracker-1.9
  tests/integration_tests/test_kani.py
Labels: Status: Awaiting review

#4769 fix(changelog): add entry about virtio-net feature negotiation fix
  CHANGELOG.md
Labels: Status: Awaiting review

#4770 Backport CHANGELOG entry about virtio-net feature negotiation fix
  CHANGELOG.md
Labels: Status: Awaiting review

#4773 chore: deduplicate emails in CREDITS.md
  .mailmap
  CREDITS.md
Labels: Priority: Low, Status: Awaiting review

#4774 fix(make_release): create the build directory as non-root
  tools/devtool
Labels: Status: Awaiting review

#4776 Backport make_release fix for creating the build directory as non-root to v1.9
  tools/devtool
Labels: Status: Awaiting review

#4777 Update CI bucket to point to v1.10
  docs/getting-started.md
  tools/devtool
Labels: Status: Awaiting review

#4779 kani: improve performance
  src/vmm/src/devices/virtio/iovec.rs
Labels: Status: Awaiting review

#4781 Update changelog
  CHANGELOG.md
Labels: Status: Awaiting review

#4743 Jailer: added the `-h` flag as a shorthand for `--help`
  CHANGELOG.md
  src/utils/src/arg_parser.rs
Labels: Status: Awaiting review

#4785 ci: start kani test without waiting for build
  .buildkite/common.py
  .buildkite/pipeline_pr.py
Labels: Status: Awaiting review

#4786 test: do not build firecracker before running kani
  .buildkite/pipeline_pr.py
Labels: Status: Awaiting review

#4148 docs: Removed unusable devctr guide
  CHANGELOG.md
  docs/devctr-image.md
Labels: Priority: Low, Status: Awaiting review

#4790 fix(release): ensure debuginfo file contains debugging info
  CHANGELOG.md
  Cargo.toml
  tests/integration_tests/functional/test_binary.py
  tests/integration_tests/functional/test_binary_static_linking.py
Labels: Priority: Low, Status: Awaiting review

#4810 chore: remove too fast benches
  src/vmm/benches/block_request.rs
  src/vmm/benches/queue.rs
Labels: Status: Awaiting review, Type: Fix, Type: Performance

#4812 fix(vsock): save state after sending a notification
  src/vmm/src/device_manager/persist.rs
  tests/integration_tests/functional/test_vsock.py
Labels: Status: Awaiting review, Type: Fix

#4814 doc: quote wget URLs to avoid copy paste escapes
  docs/getting-started.md
Labels: Status: Awaiting review

#4788 Use u32 for Vsock related buffer sizes
  src/vmm/src/devices/virtio/vsock/csm/connection.rs
  src/vmm/src/devices/virtio/vsock/packet.rs
  src/vmm/src/devices/virtio/vsock/test_utils.rs
  src/vmm/src/devices/virtio/vsock/unix/muxer.rs
Labels: Status: Awaiting review

#4821 chore: Pin m6i/5.10 AMI to last known good one
  .buildkite/pipeline_perf.py
Labels: Status: Awaiting review
