Repository firecracker-microvm/firecracker, pull requests merged in 2024-06, with the labels that each got.

#4631 [1.8] chore: update kvm-bindings to 0.8.2
  Cargo.lock
Labels: Status: Awaiting review

#4634 chore(ci): double pytest timeout duration temporarily
  tests/pytest.ini
Labels: Status: Awaiting review

#4640 fix(test_rng): do not test for virtio-rng performance
  tests/integration_tests/functional/test_rng.py
Labels: Status: Awaiting review

#4648 Add git-secrets to pre-commit
  pre-commit
Labels: Status: Awaiting review

#4653 ci: move automatic retry to BKPipeline class
  .buildkite/common.py
  .buildkite/pipeline_cross.py
  .buildkite/pipeline_perf.py
Labels: Priority: Low, Status: Awaiting review, python

#4654 Revert pytest timeout
  tests/pytest.ini
Labels: Priority: Low, Status: Awaiting review
