Repository firecracker-microvm/firecracker, pull requests merged in 2024-03, with the labels that each got.

#4478 doc: network for clones iptables dnat command error
  docs/snapshotting/network-for-clones.md
Labels: Status: Awaiting review

#4483 chore: update linux-loader to 0.11.0
  Cargo.lock
  src/utils/Cargo.toml
  src/vmm/Cargo.toml
Labels: Status: Awaiting review

#4481 fix: Have `./tools/ab_test.py analyze` actually perform an A/B-Test
  tools/ab_test.py
Labels: Status: Awaiting review

#4496 chore: remove repetitive words
  src/vmm/src/cpu_config/x86_64/cpuid/common.rs
  src/vmm/src/devices/virtio/balloon/device.rs
  src/vmm/src/devices/virtio/queue.rs
  src/vmm/src/io_uring/mod.rs
Labels: Status: Awaiting review

#4441 fix: use the right base branch to detect changed files
  .buildkite/common.py
  .buildkite/pipeline_pr.py
  .buildkite/pipeline_pr_no_block.py
Labels: Status: Awaiting review

#4512 Backport #4507
  .buildkite/common.py
  .buildkite/pipeline_pr.py
  .buildkite/pipeline_pr_no_block.py
Labels: Status: Awaiting review

#4466 doc: Getting started with internet access for first time user
  docs/getting-started.md
Labels: Status: Awaiting review

#4514 chore: Updated CHANGELOG post 1.7 release
  CHANGELOG.md
Labels: Status: Awaiting review

#4515 fix: unpin kani-verifier version in Dockerfile
  tools/devctr/Dockerfile
Labels: Status: Awaiting review

#4518 fix(ci): build Firecracker when we need to
  .buildkite/pipeline_cross.py
  tools/devtool
Labels: Priority: High, Status: Awaiting review

#4494 refactor: error_impl_error in Cargo.toml
  Cargo.toml
  src/firecracker/src/api_server/parsed_request.rs
  src/firecracker/src/api_server/request/actions.rs
  src/firecracker/src/api_server/request/balloon.rs
  src/firecracker/src/api_server/request/boot_source.rs
  src/firecracker/src/api_server/request/cpu_configuration.rs
  src/firecracker/src/api_server/request/drive.rs
  src/firecracker/src/api_server/request/entropy.rs
  src/firecracker/src/api_server/request/instance_info.rs
  src/firecracker/src/api_server/request/logger.rs
  src/firecracker/src/api_server/request/machine_configuration.rs
  src/firecracker/src/api_server/request/metrics.rs
  src/firecracker/src/api_server/request/mmds.rs
  src/firecracker/src/api_server/request/net.rs
  src/firecracker/src/api_server/request/snapshot.rs
  src/firecracker/src/api_server/request/version.rs
  src/firecracker/src/api_server/request/vsock.rs
  src/firecracker/src/main.rs
  src/firecracker/tests/verify_dependencies.rs
  src/jailer/src/env.rs
  src/jailer/src/main.rs
  src/rebase-snap/src/main.rs
  src/seccompiler/src/seccompiler_bin.rs
  src/snapshot-editor/src/utils.rs
  src/utils/src/arg_parser.rs
  src/utils/src/kernel_version.rs
  src/utils/src/validators.rs
  src/vmm/src/devices/virtio/block/virtio/device.rs
  src/vmm/src/devices/virtio/block/virtio/io/mod.rs
  src/vmm/src/dumbo/pdu/arp.rs
  src/vmm/src/dumbo/pdu/ethernet.rs
  src/vmm/src/dumbo/pdu/ipv4.rs
  src/vmm/src/dumbo/pdu/tcp.rs
  src/vmm/src/dumbo/pdu/udp.rs
  src/vmm/src/dumbo/tcp/connection.rs
  src/vmm/src/dumbo/tcp/handler.rs
  src/vmm/src/mmds/data_store.rs
  src/vmm/src/mmds/mod.rs
  src/vmm/src/mmds/ns.rs
  src/vmm/src/mmds/token.rs
  src/vmm/src/persist.rs
  src/vmm/src/rate_limiter/mod.rs
  src/vmm/src/resources.rs
  src/vmm/src/rpc_interface.rs
  src/vmm/src/snapshot/mod.rs
  src/vmm/src/vmm_config/machine_config.rs
  src/vmm/src/vmm_config/mmds.rs
Labels: Status: Awaiting review

#4528 fix(tests): lock while building in AB mode
  tests/framework/ab_test.py
Labels: Priority: Medium, Status: Awaiting author

#4526 Fail early in case of too big a frame in the TX path
  CHANGELOG.md
  src/vmm/src/devices/virtio/net/device.rs
  src/vmm/src/devices/virtio/net/test_utils.rs
Labels: Status: Awaiting review
