Repository firecracker-microvm/firecracker, pull requests merged in 2024-02, with the labels that each got.

#4427 fix: Flush metrics to cloudwatch
  tests/host_tools/fcmetrics.py
Labels: Status: Awaiting review

#4433 fix: Git blame ignore markdown re-format
  .git-blame-ignore-revs
Labels: Status: Awaiting review

#4432 fix: broken license check for dependencies
  deny.toml
  tests/integration_tests/build/test_dependencies.py
Labels: Status: Awaiting review

#4430 ci: Disable A/B tests failing on m6i.metal 6.1
  tools/ab_test.py
Labels: Status: Awaiting review

#4437 docs: Highlight getting-started.md resources are not production ready
  docs/getting-started.md
Labels: Status: Awaiting review

#4443 test: Sort tested dimensions dict by keys on A/B test failures
  tools/ab_test.py
Labels: Status: Awaiting review

#4446 doc: Correct description for pytest capturing
  tests/README.md
Labels: Status: Awaiting review

#4444 test(drive): avoid calling sync inside sfdisk
  tests/framework/utils_drive.py
Labels: Status: Awaiting review

#4448 test: reenable A/B test alarming on m6i/6.1
  tools/ab_test.py
Labels: Status: Awaiting review

#4447 fix(vmm): make VmResources.boot_source pub
  src/vmm/src/resources.rs
Labels: Status: Awaiting review

#4451 test: emit page fault metrics even on ARM
  tests/integration_tests/performance/test_huge_pages.py
Labels: Status: Awaiting review

#4455 fix(doc): Update vmlinux artifact link
  docs/getting-started.md
Labels: Status: Awaiting review

#4459 chore(buildkite): use correct kernel version for m6i/6.1
  .buildkite/pipeline_perf.py
Labels: Status: Awaiting review

#4462 tests: Install tools with `--locked` option
  tools/devctr/Dockerfile
Labels: Status: Awaiting review

#4358 chore(docs): deprecate --start-time-cpu-us parameter
  CHANGELOG.md
  docs/jailer.md
  src/firecracker/src/main.rs
  src/jailer/src/env.rs
  src/jailer/src/main.rs
  src/vmm/src/logger/metrics.rs
Labels: Priority: Low, Status: Awaiting review, Type: Documentation, Release

#4467 fix: do not limit pipeline_perf.py to nonci tests in metrics mode
  .buildkite/pipeline_perf.py
Labels: Status: Awaiting review

#4469 chore: bump version to 1.8.0-dev
  Cargo.lock
  docs/getting-started.md
  src/cpu-template-helper/Cargo.toml
  src/firecracker/Cargo.toml
  src/firecracker/swagger/firecracker.yaml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  src/snapshot-editor/Cargo.toml
  tools/devtool
Labels: Status: Awaiting review

#4471 fix: subtract pre-`run()` execution time from startup time again
  src/jailer/src/env.rs
Labels: Status: Awaiting review

#4475 Add microvm helper for enabling console data
  tests/framework/microvm.py
Labels: Status: Awaiting review, Type: Enhancement, python
