Repository firecracker-microvm/firecracker, pull requests merged in 2024-05, with the labels that each got.

#4584 Store kvi all the time
  src/vmm/src/builder.rs
  src/vmm/src/vstate/vcpu/aarch64.rs
  src/vmm/src/vstate/vcpu/mod.rs
Labels: Status: Awaiting review, Type: Enhancement

#4590 feat: store snapshot files on test fail
  tests/conftest.py
Labels: Status: Awaiting review, Type: Enhancement

#4593 fix: update fingerprint baselines for 5.10 kernel
  tests/data/cpu_template_helper/fingerprint_INTEL_CASCADELAKE_5.10host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_ICELAKE_5.10host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_SKYLAKE_5.10host.json
Labels: Status: Awaiting review, Type: Fix

#4595 doc: Troubleshooting for `ab_test.py analyze`
  tests/README.md
Labels: Status: Awaiting review

#4594 fix: update guest msr list for 5.10 host
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_5.10host_5.10guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_ICELAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_ICELAKE_5.10host_5.10guest.csv
  tests/data/msr/msr_list_T2S_INTEL_CASCADELAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2S_INTEL_CASCADELAKE_5.10host_5.10guest.csv
  tests/data/msr/msr_list_T2S_INTEL_ICELAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2S_INTEL_ICELAKE_5.10host_5.10guest.csv
Labels: Status: Awaiting review, Type: Fix

#4585 Derived Error and Display Updates
  src/firecracker/src/main.rs
  src/jailer/src/main.rs
  src/rebase-snap/src/main.rs
  src/seccompiler/src/backend.rs
  src/snapshot-editor/src/edit_memory.rs
  src/vmm/src/arch/aarch64/vcpu.rs
  src/vmm/src/lib.rs
  src/vmm/src/rpc_interface.rs
  src/vmm/src/vmm_config/balloon.rs
  src/vmm/src/vmm_config/drive.rs
  src/vmm/src/vmm_config/vsock.rs
  src/vmm/src/vstate/memory.rs
  tests/integration_tests/functional/test_api.py
  tests/integration_tests/functional/test_cmd_line_start.py
Labels: Status: Awaiting review

#4596 test: stop all monitors before killing microvm
  tests/framework/microvm.py
  tests/host_tools/fcmetrics.py
  tests/host_tools/memory.py
Labels: Priority: Low, Status: Awaiting review, python

#4605 test: add a global dimension to test failure metric
  tests/conftest.py
Labels: Priority: Low, Status: Awaiting review

#4606 fix(snapshot): prevent an integer overflow when calculating TSC scaling
  src/vmm/src/vstate/vcpu/x86_64.rs
Labels: Priority: Medium, Status: Awaiting author

#4599 Efficiency TODO in endpoint.rs
  src/vmm/src/dumbo/tcp/endpoint.rs
Labels: Status: Awaiting review

#4600 Reduce test verbosity in arp.rs TODO
  src/vmm/src/dumbo/pdu/arp.rs
Labels: Status: Awaiting review

#4592 Add recent changes to CHANGELOG.md
  CHANGELOG.md
Labels: Status: Awaiting review

#4610 Decrease logging in test_rng tests
  tests/integration_tests/functional/test_rng.py
Labels: Priority: Low, Status: Awaiting author

#4612 fix(test): re-enable tests
  tests/integration_tests/security/test_vulnerabilities.py
Labels: Priority: Medium, Status: Awaiting review

#4613 fix(test): avoid parsing broken metrics lines
  tests/framework/microvm.py
  tests/integration_tests/security/test_custom_seccomp.py
Labels: Priority: Low, Status: Awaiting review

#4614 feat: use host network for docker
  tools/devtool
Labels: Status: Awaiting review

#4617 Revert "feat: use host network for docker"
  tools/devtool
Labels: Status: Awaiting review

#4616 fix(cpu-template-helper): Fix error message display
  src/cpu-template-helper/src/fingerprint/compare.rs
  src/cpu-template-helper/src/main.rs
Labels: Status: Awaiting review

#4556 Change IoVecBuffer[Mut] len to u32
  src/vmm/src/devices/virtio/iovec.rs
  src/vmm/src/devices/virtio/net/device.rs
  src/vmm/src/devices/virtio/net/tap.rs
  src/vmm/src/devices/virtio/rng/device.rs
  src/vmm/src/devices/virtio/vsock/mod.rs
  src/vmm/src/devices/virtio/vsock/packet.rs
Labels: Status: Awaiting review

#4626 ci: output disk usage if tests fail
  tools/test.sh
Labels: Priority: Medium, Status: Awaiting review

#4629 fix(ci): ignore errors so we can capture the exit status
  tools/test.sh
Labels: Priority: Low, Status: Awaiting review
