Repository firecracker-microvm/firecracker, pull requests merged in 2024-10, with the labels that each got.

#4828 fix memory access benchmark panicking on ARM
  src/vmm/benches/memory_access.rs
Labels: Status: Awaiting review

#4830 test: increase timeout on benchmarks
  tests/integration_tests/performance/test_benchmarks.py
Labels: Status: Awaiting review

#4823 test: mark boottime and memory overhead tests as nonci
  tests/integration_tests/performance/test_boottime.py
  tests/integration_tests/performance/test_memory_overhead.py
Labels: Status: Awaiting review

#4835 test(net): add test for tap offload features
  tests/host_tools/udp_offload.py
  tests/integration_tests/functional/test_net.py
Labels: Status: Awaiting review

#4838 doc(swagger): add cpu-config and entropy in vm config
  src/firecracker/swagger/firecracker.yaml
Labels: Status: Awaiting review

#4712 Cleaning up create_fdt
  src/vmm/src/arch/aarch64/fdt.rs
  src/vmm/src/arch/aarch64/mod.rs
Labels: Status: Awaiting review

#4846 Reuse buffer for processing descriptor chains in virtio-rng device
  src/vmm/src/devices/virtio/rng/device.rs
Labels: Status: Awaiting review, Type: Enhancement, Type: Performance

#4847 fix(ci): epoll on pidfd to wait for Firecracker exit
  tests/framework/utils.py
Labels: Status: Awaiting review

#4853 test: move "doing A/B-Test" print statement below ignore-check
  tools/ab_test.py
Labels: Status: Awaiting review

#4857 chore: don't update dependencies when with new vX.Y.0-dev version
  tools/bump-version.sh
Labels: Status: Awaiting review

#4865 chore: unpin 5.10/m6i ami
  .buildkite/pipeline_perf.py
Labels: Status: Awaiting review, Type: Fix

#4871 Add CHANGELOG entry on support of ARM systems with big caches
  CHANGELOG.md
Labels: Status: Awaiting review, Type: Documentation

#4872 Revert "chore: unpin 5.10/m6i ami"
  .buildkite/pipeline_perf.py
Labels: Status: Awaiting review, Type: Fix

#4880 Update test_deflate_on_oom test
  tests/integration_tests/functional/test_balloon.py
Labels: Status: Awaiting review

#4883 chore: update CHANGELOG with virtio-net changes
  CHANGELOG.md
Labels: Status: Awaiting review, Type: Documentation, Type: Fix
