Repository firecracker-microvm/firecracker, pull requests merged in 2024-01, with the labels that each got.

#4340 Add option to run A/B-test on two arbitrary test-report.json files
  .buildkite/pipeline_perf.py
  tools/ab_test.py
Labels: Status: Awaiting review

#4353 Bump rust-vmm dependencies
  Cargo.lock
  Cargo.toml
  src/firecracker/Cargo.toml
  src/snapshot/Cargo.toml
  src/utils/Cargo.toml
  src/vmm/Cargo.toml
  src/vmm/src/vstate/vcpu/mod.rs
  tests/integration_tests/functional/test_shut_down.py
Labels: Status: Awaiting review

#4357 Fix test `test_shut_down::test_reboot` failure in Ubuntu tests with 6.2 kernel
  tests/integration_tests/functional/test_shut_down.py
Labels: Status: Awaiting review

#4359 fix(test): error messages in msr tests
  tests/integration_tests/functional/test_cpu_features.py
Labels: Status: Awaiting review, Type: Fix

#4368 chore: move aarch64 CPU template tests to al2023
  .buildkite/pipeline_cpu_template.py
Labels: Priority: Medium, Status: Awaiting review

#4369 fix: update msr baseline
  tests/data/msr/msr_list_T2A_AMD_MILAN_4.14host_4.14guest.csv
  tests/data/msr/msr_list_T2A_AMD_MILAN_4.14host_5.10guest.csv
  tests/data/msr/msr_list_T2A_AMD_MILAN_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2A_AMD_MILAN_5.10host_5.10guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_4.14host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_4.14host_5.10guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_CASCADELAKE_5.10host_5.10guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_ICELAKE_4.14host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_ICELAKE_4.14host_5.10guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_ICELAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2CL_INTEL_ICELAKE_5.10host_5.10guest.csv
  tests/data/msr/msr_list_T2S_INTEL_CASCADELAKE_4.14host_4.14guest.csv
  tests/data/msr/msr_list_T2S_INTEL_CASCADELAKE_4.14host_5.10guest.csv
  tests/data/msr/msr_list_T2S_INTEL_CASCADELAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2S_INTEL_CASCADELAKE_5.10host_5.10guest.csv
  tests/data/msr/msr_list_T2S_INTEL_ICELAKE_4.14host_4.14guest.csv
  tests/data/msr/msr_list_T2S_INTEL_ICELAKE_4.14host_5.10guest.csv
  tests/data/msr/msr_list_T2S_INTEL_ICELAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2S_INTEL_ICELAKE_5.10host_5.10guest.csv
  tests/data/msr/msr_list_T2S_INTEL_SKYLAKE_4.14host_4.14guest.csv
  tests/data/msr/msr_list_T2S_INTEL_SKYLAKE_4.14host_5.10guest.csv
  tests/data/msr/msr_list_T2S_INTEL_SKYLAKE_5.10host_4.14guest.csv
  tests/data/msr/msr_list_T2S_INTEL_SKYLAKE_5.10host_5.10guest.csv
Labels: Status: Awaiting review

#4372 fix: Add check for known vulnerabilities in guest
  tests/integration_tests/security/test_vulnerabilities.py
Labels: Status: Awaiting review

#4315 Revert "ci: Disable A/B tests failing on m6i.metal 5.10"
  tools/ab_test.py
Labels: Status: Awaiting review

#4390 Fix: Add library target to src/firecracker crate
  src/firecracker/Cargo.toml
  src/firecracker/src/api_server/mod.rs
  src/firecracker/src/lib.rs
Labels: Status: Awaiting review

#4392 Mark Firecracker v1.4 as EOL
  docs/RELEASE_POLICY.md
Labels: Priority: Low, Status: Awaiting review, Type: Documentation

#4394 chore(deps): run cargo update to update shlex
  Cargo.lock
Labels: Priority: High, Status: Awaiting review, dependencies

#4397 [bp v1.6] chore(deps): run cargo update to update shlex
  Cargo.lock
Labels: Priority: High, Status: Awaiting review, dependencies

#4398 [bp v1.5] chore(deps): run cargo update to update shlex
  Cargo.lock
Labels: Priority: High, Status: Awaiting review, dependencies

#4401 ci(perf/net_latency): increase absolute delta threshold to 10us
  .buildkite/pipeline_perf.py
  tools/ab_test.py
Labels: Priority: Medium, Status: Awaiting review

#4403 test: fix test_partuuid_boot
  tests/framework/utils_drive.py
Labels: Priority: High, Status: Awaiting review, Type: Fix

#4407 test: Use structured matching on cpu properties
  tests/framework/utils_cpu_templates.py
Labels: Status: Awaiting review

#4417 ab: Do not fail with summary listing values below noise threshold
  tools/ab_test.py
Labels: Status: Awaiting review
