Repository firecracker-microvm/firecracker, pull requests merged in 2024-11, with the labels that each got.

#4892 chore: Update release policy
  docs/RELEASE_POLICY.md
Labels: Status: Awaiting review

#4897 chore: bump version to 1.11.0-dev
  Cargo.lock
  src/cpu-template-helper/Cargo.toml
  src/firecracker/Cargo.toml
  src/firecracker/swagger/firecracker.yaml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  src/snapshot-editor/Cargo.toml
Labels: Status: Awaiting review

#4902 chore: release v1.10.0
  CHANGELOG.md
  CREDITS.md
  Cargo.lock
  src/cpu-template-helper/Cargo.toml
  src/firecracker/Cargo.toml
  src/firecracker/swagger/firecracker.yaml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  src/snapshot-editor/Cargo.toml
Labels: Status: Awaiting review

#4893 test(net): use iperf3-vsock to avoid iperf crashes on aarch64
  tests/integration_tests/functional/test_net.py
Labels: Priority: Medium, Status: Awaiting review

#4903 chore: Update changelog with v1.10.0 section
  CHANGELOG.md
Labels: Status: Awaiting review

#4904 chore(test): Double refill time for RX rate limiter
  src/vmm/src/devices/virtio/net/device.rs
Labels: Status: Awaiting review

#4907 chore: Bump snapshot version
  CHANGELOG.md
  src/vmm/src/persist.rs
Labels: Status: Awaiting review

#4909 chore: update PR checklist
  .github/pull_request_template.md
Labels: Status: Awaiting review

#4911 test: test ARM CPU templates in Linux host 5.10
  tests/framework/utils_cpu_templates.py
Labels: Priority: High, Status: Awaiting review, python

#4914 chore: Update to v1.10.1 patch
  docs/RELEASE_POLICY.md
Labels: Status: Awaiting review

#4890 fix: devtool install --path broken
  tools/devtool
Labels: Status: Awaiting review, Type: Fix

#4920 ci: infer instance architecture from a heuristic
  .buildkite/common.py
  .buildkite/pipeline_cpu_template.py
Labels: Priority: Medium, Status: Awaiting review, Type: Fix

#4922 Improve network-setup with nft support and further instructions.
  docs/network-setup.md
Labels: Status: Awaiting review, Type: Documentation

#4917 refactor: Remove some getters and setters for boot_source
  src/vmm/src/builder.rs
  src/vmm/src/persist.rs
  src/vmm/src/resources.rs
Labels: Status: Awaiting review

#4928 docs: fix Firecracker version and rootfs
  docs/getting-started.md
Labels: Priority: Medium, Status: Awaiting review, Type: Documentation, Type: Fix

#4931 fix: ensure ci artifacts are present when using devtool sandbox
  tools/devtool
Labels: Status: Awaiting review

#4932 fix: properly setup outbound network connectivity in getting started
  docs/getting-started.md
Labels: Status: Awaiting review
