Repository firecracker-microvm/firecracker, pull requests merged in 2024-08, with the labels that each got.

#4715 Unpin m6i 6 1
  .buildkite/pipeline_perf.py
Labels: Status: Awaiting review, Type: Performance

#4716 fix(ab): do not leave around tmp branches
  .buildkite/common.py
  tests/framework/ab_test.py
Labels: Status: Awaiting review

#4718 Fixes minor variable naming issue in getting-started.md
  docs/getting-started.md
Labels: Status: Awaiting review

#4719 test: cause failure if FC emits an error metric
  tests/framework/microvm.py
  tests/host_tools/fcmetrics.py
  tests/integration_tests/performance/test_block_ab.py
  tests/integration_tests/performance/test_memory_overhead.py
  tests/integration_tests/performance/test_network_ab.py
  tests/integration_tests/performance/test_snapshot_ab.py
  tests/integration_tests/performance/test_vsock_ab.py
Labels: Status: Awaiting review

#4589 Reuse the IoVecBuffer on TX
  src/vmm/src/devices/virtio/iovec.rs
  src/vmm/src/devices/virtio/net/device.rs
  src/vmm/src/devices/virtio/vsock/packet.rs
Labels: Status: Awaiting author

#4727 metrics: dump the error metrics during failure
  tests/host_tools/fcmetrics.py
Labels: Status: Awaiting review

#4723 virtio: skip redundant memory check
  src/vmm/src/devices/virtio/queue.rs
Labels: Status: Awaiting review

#4739 test(ballon): add wait_for_up in test_deflate_on_oom
  tests/integration_tests/functional/test_balloon.py
Labels: Status: Awaiting review

#4738 test(jailer): do not kill screen with new_pid_ns
  tests/framework/microvm.py
Labels: Status: Awaiting review

#4438 test(jailer): enable multi-threaded test
  src/jailer/src/cgroup.rs
  src/jailer/src/env.rs
  src/jailer/src/main.rs
  src/jailer/src/resource_limits.rs
Labels: Priority: Low, Status: Awaiting review

#4749 tests: capture host dmesg on test failure
  tests/conftest.py
Labels: Status: Awaiting review, python

#4752 ci: unpin m6i/5.10 AMI
  .buildkite/pipeline_perf.py
Labels: Priority: Medium, Status: Awaiting review

#4755 Declare support for 6.1 guest kernels and deprecation for 4.14.
  CHANGELOG.md
  docs/kernel-policy.md
Labels: Status: Awaiting review

#4756 snapshot-editor: fix rebase command description
  src/snapshot-editor/src/edit_memory.rs
Labels: Priority: Medium, Status: Awaiting review

#4759 Update RELEASE_POLICY table with v1.9 release
  docs/RELEASE_POLICY.md
Labels: Status: Awaiting review

#4758 tests: fix console_data if not under screen
  tests/framework/microvm.py
Labels: Type: Bug, Priority: Medium, Status: Awaiting review

#4760 snapshot: bump version
  src/vmm/src/persist.rs
Labels: Status: Awaiting review
