Repository firecracker-microvm/firecracker, pull requests merged in 2025-09, with the labels that each got.

#5418 Fix typo in swagger
  src/firecracker/swagger/firecracker.yaml
Labels: Status: Awaiting review

#5425 chore(buildkite): add pipeline definition for release QA
  .buildkite/common.py
  .buildkite/pipeline_release_qa.py
Labels: Status: Awaiting review

#5430 test(perf/vsock): copy iperf binary only once
  tests/integration_tests/performance/test_vsock.py
Labels: Status: Awaiting review

#5428 refactor: remove TLS from vcpus
  src/vmm/src/builder.rs
  src/vmm/src/gdb/event_loop.rs
  src/vmm/src/gdb/mod.rs
  src/vmm/src/gdb/target.rs
  src/vmm/src/lib.rs
  src/vmm/src/vstate/vcpu.rs
Labels: Status: Awaiting review, Type: Enhancement

#5443 Gracefully clean-up potentially dead microVMs
  tests/framework/microvm.py
  tests/host_tools/network.py
  tests/integration_tests/functional/test_balloon.py
Labels: Status: Awaiting review

#5455 fix: correctly set device status to 0 on reset
  src/vmm/src/devices/virtio/transport/pci/device.rs
Labels: Status: Awaiting review, Type: Fix
