Repository firecracker-microvm/firecracker, pull requests merged in 2025-04, with the labels that each got.

#5129 chore: update bincode to 2.0
  Cargo.lock
  src/firecracker/examples/seccomp/jailer.rs
  src/firecracker/examples/seccomp/panic.rs
  src/firecracker/src/seccomp.rs
  src/seccompiler/Cargo.toml
  src/seccompiler/src/lib.rs
  src/vmm/Cargo.toml
  src/vmm/src/mmds/token.rs
  src/vmm/src/seccomp.rs
  src/vmm/src/snapshot/mod.rs
Labels: Status: Awaiting review

#5134 Update kernel install script to work with AL2023
  resources/hiding_ci/build_and_install_kernel.sh
  resources/hiding_ci/dkms.conf
  resources/hiding_ci/install_ena.sh
Labels: Status: Awaiting review

#5137 CI: Reshuffle perf steps a bit to better utilize workers
  .buildkite/pipeline_perf.py
Labels: Status: Awaiting review

#5141 Fix package installation for secret hiding test
  tests/integration_tests/build/test_hiding_kernel.py
Labels: Status: Awaiting review

#5149 fix(vmm): Bump snapshot version
  CHANGELOG.md
  src/vmm/src/persist.rs
Labels: Status: Awaiting author

#5148 chore: add Graviton4 instances to the bk pipelines
  .buildkite/common.py
  README.md
Labels: Status: Awaiting review, Type: Enhancement

#5150 fix: dont fail silently on awscli errors during artifact setup
  tools/devtool
Labels: Status: Awaiting review

#5147 Fix SH install script exiting too early
  resources/hiding_ci/build_and_install_kernel.sh
Labels: Status: Awaiting review

#5151 refactor: de-generify async_io engine
  src/vmm/src/devices/virtio/block/virtio/device.rs
  src/vmm/src/devices/virtio/block/virtio/io/async_io.rs
  src/vmm/src/devices/virtio/block/virtio/io/mod.rs
  src/vmm/src/devices/virtio/block/virtio/request.rs
Labels: Status: Awaiting review

#5165 Move snapshot feature to GA
  CHANGELOG.md
  docs/snapshotting/snapshot-support.md
  src/vmm/src/rpc_interface.rs
Labels: Status: Awaiting review

#5159 ci: intermittent failures fixes
  tests/integration_tests/functional/test_balloon.py
Labels: Status: Awaiting review, Type: Fix
