Repository firecracker-microvm/firecracker, pull requests merged in 2025-05, with the labels that each got.

#5175 allow specifying custom cpu template inline in config json
  CHANGELOG.md
  src/vmm/src/resources.rs
Labels: Status: Awaiting review

#5185 Hiding CI install script store kernel config in boot
  resources/hiding_ci/build_and_install_kernel.sh
Labels: Status: Awaiting review

#5199 test: run A/B tests for feature branches
  .github/workflows/trigger_ab_tests.yml
Labels: Status: Awaiting review

#5198 chore: release v1.12.0
  .mailmap
  CREDITS.md
  Cargo.lock
  src/cpu-template-helper/Cargo.toml
  src/firecracker/Cargo.toml
  src/firecracker/swagger/firecracker.yaml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  src/snapshot-editor/Cargo.toml
Labels: Status: Awaiting review

#5189 fix(ab): do not crash during printing of dimensions
  tools/ab_test.py
Labels: Status: Awaiting review

#5184 fix: do not error during pytest teardown after test failure
  tests/conftest.py
Labels: Status: Awaiting review

#5200 Enable tracing mode for release.sh and fix release.sh
  tools/release.sh
Labels: Status: Awaiting review

#5207 feat(ci): add paralellism option to bk pipelines
  .buildkite/common.py
Labels: Status: Awaiting review, Type: Enhancement

#5205 test(conftest): dump VM metrics on test failure
  tests/conftest.py
Labels: Status: Awaiting review

#5208 chore(test): Unify guest memory dimension
  tests/integration_tests/performance/test_boottime.py
Labels: Status: Awaiting review

#5209 chore(ci): don't store latency for libaio
  tests/integration_tests/performance/test_block_ab.py
Labels: Status: Awaiting review, Type: Performance

#5210 Split post-snapshot checks for steal time test
  tests/integration_tests/functional/test_steal_time.py
Labels: Status: Awaiting review

#5214 doc(net): remove instruction for nameserver setup via boot_args
  docs/network-setup.md
Labels: Status: Awaiting review

#5218 chore(metric): add per-test metric dimension for coarse grained metrics
  tests/conftest.py
Labels: Status: Awaiting review

#5220 fix(test): resolve regex library warnings
  tests/host_tools/proc.py
Labels: Status: Awaiting review

#5224 example(uffd): handle EAGAIN from UFFDIO_ZEROPAGE
  src/firecracker/examples/uffd/uffd_utils.rs
Labels: Status: Awaiting review

#5230 test: display the cpu template name
  tests/integration_tests/functional/test_cpu_features_x86_64.py
Labels: Status: Awaiting review
