Repository firecracker-microvm/firecracker, pull requests merged in 2025-01, with the labels that each got.

#4976 ci: print EC2 AMI in the pytest report header
  tests/conftest.py
Labels: Priority: Low, Status: Awaiting review, python

#4979 ci: fix passing simple values to step parameters
  .buildkite/common.py
Labels: Type: Bug, Status: Awaiting review, python

#4978 chore(vmm): Add pointer alignment check for Queue
  src/vmm/src/devices/virtio/queue.rs
Labels: Status: Awaiting review

#4981 fix: stop messing with C-states in performance tests
  tools/devtool
Labels: Status: Awaiting review

#4986 CI: also test amazonlinux:2023 in the popular containers test
  tools/test-popular-containers/build_rootfs.sh
Labels: Priority: Low, Status: Awaiting review

#4999 feat: more descriptive panic messages in uffd examples
  src/firecracker/examples/uffd/uffd_utils.rs
Labels: Status: Awaiting review, Type: Enhancement

#4996 docs: Update documentation on balloon device
  docs/ballooning.md
Labels: Status: Awaiting review, Type: Documentation

#5002 Tests: test_kvm_ptp: wait up to 5s for the device to appear.
  tests/integration_tests/functional/test_kvm_ptp.py
Labels: Priority: Low, Status: Awaiting review, Type: Fix, python

#5008 fix: make style checks fail if either test fails
  tools/devtool
Labels: Type: Bug, Priority: High, Status: Awaiting review

#5000 fix: clarify comments in kani module
  src/vmm/src/devices/virtio/queue.rs
Labels: Status: Awaiting review

#5010 test: sync fs before checking for output file
  tests/integration_tests/functional/test_net.py
Labels: Priority: Medium, Status: Awaiting review, Type: Fix, python

#5016 Fix(test): have codecov uploader exit with non-zero code on error
  tests/integration_tests/build/test_coverage.py
Labels: Status: Awaiting review
