Repository firecracker-microvm/firecracker, pull requests merged in 2025-03, with the labels that each got.

#5058 Doc updates in preparation for 1.11 release
  CHANGELOG.md
Labels: Status: Awaiting review

#5060 chore: bump version to 1.12.0-dev
  Cargo.lock
  src/cpu-template-helper/Cargo.toml
  src/firecracker/Cargo.toml
  src/firecracker/swagger/firecracker.yaml
  src/jailer/Cargo.toml
  src/rebase-snap/Cargo.toml
  src/seccompiler/Cargo.toml
  src/snapshot-editor/Cargo.toml
Labels: Status: Awaiting review

#5070 Revert "test: skip test_gitlint on PR #5048"
  tests/integration_tests/style/test_gitlint.py
Labels: Status: Awaiting review

#5062 fix: Allow jailer to continue with partial CPU cache info
  src/jailer/src/env.rs
Labels: Status: Awaiting review

#5071 Jailer tweaks
  src/jailer/src/env.rs
Labels: Status: Awaiting review, Type: Fix

#5072 chore(aarch64): increase the max_value for timer reset test
  src/vmm/src/arch/aarch64/vcpu.rs
Labels: Status: Awaiting review

#5093 [v1.11] ignore paste in cargo audit
  .cargo/audit.toml
Labels: Status: Awaiting review

#5094 chore(doc): remove arm64 snapshot reg length limitation
  docs/snapshotting/snapshot-support.md
Labels: Status: Awaiting review, Type: Documentation

#4948 fix: rename page_size_kib to page_size
  CHANGELOG.md
  src/firecracker/examples/uffd/uffd_utils.rs
  src/vmm/src/persist.rs
  src/vmm/src/vmm_config/machine_config.rs
Labels: Status: Awaiting review

#5097 Try to make UFFD handlers more robust
  src/firecracker/examples/uffd/uffd_utils.rs
Labels: Status: Awaiting review

#5099 adjust G4 guest features with sve+pac cpu template
  tests/integration_tests/functional/test_cpu_features_aarch64.py
Labels: Status: Awaiting review, Type: Fix

#5103 Sleep between retries during UFFD handler negotiation
  src/firecracker/examples/uffd/uffd_utils.rs
Labels: Status: Awaiting review

#5102 test: increase cases for test_population_latency
  tests/integration_tests/performance/test_snapshot_ab.py
Labels: Status: Awaiting review

#5101 [1.10 Backport] Revert "fix: test_sec_audit: ignore cargo audit output"
  tests/integration_tests/security/test_sec_audit.py
Labels: Status: Awaiting review

#5104 doc: clarify kernel configuration usage in our repo
  docs/kernel-policy.md
Labels: Status: Awaiting review, Type: Documentation

#5110 refactor: don't duplicate VIRTIO_F_* constants in generated modules
  src/vmm/src/devices/virtio/balloon/device.rs
  src/vmm/src/devices/virtio/block/vhost_user/device.rs
  src/vmm/src/devices/virtio/block/virtio/device.rs
  src/vmm/src/devices/virtio/generated/mod.rs
  src/vmm/src/devices/virtio/generated/virtio_blk.rs
  src/vmm/src/devices/virtio/generated/virtio_config.rs
  src/vmm/src/devices/virtio/generated/virtio_net.rs
  src/vmm/src/devices/virtio/net/device.rs
  src/vmm/src/devices/virtio/rng/device.rs
  src/vmm/src/devices/virtio/vsock/device.rs
  src/vmm/src/devices/virtio/vsock/mod.rs
  tools/bindgen.sh
Labels: Status: Awaiting review

#5116 tests: Report kernels newer than 6.12 as next
  tests/conftest.py
  tests/framework/microvm.py
  tests/framework/properties.py
  tests/host_tools/fcmetrics.py
  tests/integration_tests/performance/test_boottime.py
Labels: Status: Awaiting review

#5119 test(conftest): move (not copy) vm artifacts
  tests/conftest.py
Labels: Status: Awaiting review

#5118 vmm: Disable WAITPKG
  CHANGELOG.md
  docs/cpu_templates/cpuid-normalization.md
  src/vmm/src/cpu_config/x86_64/cpuid/intel/normalize.rs
  tests/data/cpu_template_helper/fingerprint_INTEL_SAPPHIRE_RAPIDS_5.10host.json
  tests/data/cpu_template_helper/fingerprint_INTEL_SAPPHIRE_RAPIDS_6.1host.json
Labels: Status: Awaiting review

#5122 fix(vmm/persist): do not close uffd socket
  CHANGELOG.md
  src/vmm/src/persist.rs
Labels: Status: Awaiting review
